### ISSUE TITLE
Publish pyrsia-node release for MacOSX with M1 processor

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1012]
We would like to present Pyrsia at Kubecon in Oct 2022 and would like to make it possible for developers to try pyrsia installations with minimum friction. We need to release binaries for pyrsia-node that are compatible with MacOSX(M1 arch) so that Mac developers can easily engage.

Explore: If this requires any special configuration after we have built a version that works on Mac(Intel arch)

**Comment by karolh2000** [comment]
Our current brew installer covers M1, closing this issue.
