### ISSUE TITLE
Explore: Steps needed to install pyrsia_node via Homebrew

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1046]
Simple installation like

`brew tap mycompany/packages`
`brew install mycompany/packages/pyrsia`

**Comment by betarelease** [comment]
Blogs that describe how homebrew expects your app to be to be installable with brew


https://kevin.burke.dev/kevin/install-homebrew-go/

https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/

https://jldlaughlin.medium.com/how-does-homebrew-work-starring-rust-94ae5aa24552

**Comment by jperedadnr** [comment]
Looking into this, I've found this site that lists several crates as command line utilities, that can be installed in different ways, including brew:

https://crates.io/categories/command-line-utilities

for instance, `lsd` tool: https://crates.io/crates/lsd, https://github.com/Peltoche/lsd

it has brew installer: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lsd.rb

And also for Windows, via scoop.

**Comment by dasmanas** [comment]
# Things to be accomplished
## Ruby script
A ruby script has to be created under Formula subdirectory.
 

## A Cloud Bucket
Create a cloud  bucket for the installer archives to be available publicly to enable downloads.
