### ISSUE TITLE
Create a space on GCS to store all the windows installers with versions (similar to what we have for debian)

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1119]

**Comment by betarelease** [comment]
@sbtaylor15 can you please work with @jperedadnr on getting this setup with the github actioins. I created this so that we do not lose track of this final step in publishing the release.

**Comment by erwin1** [comment]
@sbtaylor15 this was setup, right?
although we decided in the meanwhile to provide the .msi file from the GitHub release page

**Comment by betarelease** [comment]
We already have a folder on GCS for windows.
