### ISSUE TITLE
Allow easier (port) CLI configuration

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1131]
allow for easier configuration: 
- when I want to switch between 2 nodes on the same localhost
- I have to go through the config wizard every time, just to change the port number

It would be nice if I could change the Pyrsia CLI port via one command:

e.g.
```
pyrsia config edit --port 7888
```

and maybe even do this for every config option. 
This way, we can still allow the host to be configured but remove it from the config wizard as specified in #1106

**Comment by dasmanas** [comment]
After analyzing the implementation, it seems there is no real need of keeping `pyrsia config -a` or `pyrsia config --add`. App getting the config by `config::get_config` and if there is no config, it creates a config with default values.

**Comment by dasmanas** [comment]
Feature is implemented using #1251
