### ISSUE TITLE
Docker integration response hardcode some information

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#114]
Playing with the implementation I noticed a small limitation

- hostname
- port

**Comment by prince-chrismc** [comment]
https://github.com/pyrsia/pyrsia/blob/35ddbab30b2e50c66390ba9e0f8bb88aca196273/src/docker/v2/handlers/blobs.rs#L96

Still true 🤔

**Comment by betarelease** [comment]
Closing because it is outdated and code has evolved.
