### ISSUE TITLE
Minor comments to 'Pyrsia demo: build Docker images/Maven artifacts from source' tutorials

### ISSUE THREAD

**Issue by jperedadnr** [pyrsia/pyrsia#1146]
The tutorial **Pyrsia demo: build Docker images from source** works fine end to end, but with a few observations:

- typo in https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_docker.md#authorize-node-a-as-a-build-node

It says:
```
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB):
10GB
```
But it should be:
```
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB):
10 GB
```

- typo in https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_docker.md#authorize-node-a-as-a-build-node

It says:
```
curl -s http://localhost:7888/status | jq  .peer_id
```
But it should be:
```
curl -s http://localhost:7889/status | jq  .peer_id
```

- In https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_docker.md#trigger-a-build-from-source-for-a-given-artifact

The request to build is done from nodeB, and the build is done in nodeA. It says:

```
Build request successfully handled. Build with ID c9ca3e57-aa84-4fab-a8be-381ab31e4916 has been started.
```
but actually it returns:
```
Build request successfully handled. Build with ID 1 has been started.
```
Since the build is requested through the p2p network, the nodeA doesn't expose the build ID, and the response is based on a local counter in nodeB (it will increase on subsequent requests).
 
Only when the build is requested directly on an authorized node (nodeA in this case), the build is local, and it exposes the build ID.

**Pyrsia demo: build Maven artifacts from source**

- Title is wrong: 

says: `Pyrsia demo: build Docker images from source`
should say: `Pyrsia demo: build Maven artifacts from source`

- typo in https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_maven.md#authorize-node-a-as-a-build-node

It says:
```
curl -s http://localhost:7888/status | jq  .peer_id
```
But it should be:
```
curl -s http://localhost:7889/status | jq  .peer_id
```

**Comment by betarelease** [comment]
I think the functionality related to returning the correct build id was updated in #1321. Can @karolh2000 or @tiainen update the documentation to reflect that change and close this?
