### ISSUE TITLE
Fix Version Hardcoding replacement of archives / toml for build-osx jobs

### ISSUE THREAD

**Issue by dasmanas** [pyrsia/pyrsia#1163]
### Steps taken/Steps to reproduce

Currently `0.1.0` hardcoded in the build job. Support fluid versioning as per semver

### Expected Behavior

Create archives with correct versioning even when we use anything else other than `0.1.0`

### Experienced Instance of the bug

Rust Version: 1.63
OS: Mac OSX

**Comment by sbtaylor15** [comment]
cargo.toml, GH Action have been updated in PR #1157

**Comment by dasmanas** [comment]
I put something like following.
```
sed -ir.bak 's/\(^version = \"\)\([[:digit:]]\(.[[:digit:]]\+\)\+\)\(.*\)\(\"$\)/\1\2\4+0987654321\5/' Cargo.toml
```
It will take care cases like

- `version = "1.2.3"`
- `version = "1.2.3-rc"`
- `version = "1.2.34.5"`

**Comment by dasmanas** [comment]
Closed by https://github.com/pyrsia/pyrsia/pull/1173
