### ISSUE TITLE
Deploy Python App for Homebrew repo to generate index.html files for all subdirectories in a directory tree

### ISSUE THREAD

**Issue by dasmanas** [pyrsia/pyrsia#1166]
### Suggestion details

Deploy Python App Homebrew repo to enable downloads from cloud buckets

**Comment by betarelease** [comment]
Can you elaborate on how this Python app helps? I did not understand where we would need Python.

**Comment by dasmanas** [comment]
The brew will access the cloud location for the installer archive. The location will be mentioned in Formula.rb file. As per policy we can't give public access to Google bucket. Therefore the download happens through a Python application (e.g. debrepo - https://repo.pyrsia.io/).

**Comment by betarelease** [comment]
Ahh. In that case we can use something cloud native - like a CDN to serve those files. Adding python will mean now we have to support another language ecosystem and keep on maintaining that which I am looking to avoid.

**Comment by dasmanas** [comment]
Installer archive is going to be stored in cloud bucket which will be referred from brew ruby script. Due to org policy we can't make cloud bucket public. Therefore Nginx service is providing the gateway to download installer. Additionally if we want a directory listing UI for the bucket, we need to run `python3 .github/workflows/genlisting.py -r` from the root of your local bucket. We may skip this as without this service we are still able to achieve our target.

**Comment by dasmanas** [comment]
Closed by https://github.com/pyrsia/pyrsia/pull/1210/files
