### ISSUE TITLE
Move Model to pyrsia_client_lib

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#117]
The struct that we will use to represent metadata are defined in the model module. These struct represent things like Packages, PackageVersions and artifacts. These are things that we will need to deal with both within the node and in the CLI. 

For this reason, the model module should be moved to pyrsia_client_lib. That is the library crate that will contain common modules to be used by both the node and the CLI (and any other Pyrsia clients).

**Comment by prince-chrismc** [comment]
I disagree. We discussed not having vague names like "utils" and client lib is not descriptive.

Also there no need for this single folder to share. Cargo allows and recommends using relative path to internal grates.

Models can be more into the `src` directory with a toml for other to include it if they so wish.

**Comment by mgrand** [comment]
Given the discussion we had today where we will keep everything in one big crate, at least until the demo, there is no point to doing this now.  I am moving this to the after demo column.
