### ISSUE TITLE
Inspect log has no port option and fails when you start pyrsia_node on any port that isn't 7888

### ISSUE THREAD

**Issue by efrisch** [pyrsia/pyrsia#1171]
### Steps taken/Steps to reproduce

Start pyrsia on a non-standard port
`pyrsia_node -H 0.0.0.0 -p 7889 -L /ip4/0.0.0.0/tcp/44004`

Then run

`pyrsia inspect-log docker --image alpine:3.16`

Inspect log request failed with error: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(7888), path: "/inspect/docker", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })) }

### Expected Behavior

Expect to be able to override the port and run inspect log

### Experienced Instance of the bug

Rust version: rustc 1.63.0 (4b91a6ea7 2022-08-08)
Operating system: macOS (but relevant to all)
Pyrsia Version: `main` (as of 2022-10-10) and `0.2`

**Comment by erwin1** [comment]
also related to #1131

**Comment by fishseabowl** [comment]
The command line arguments don't look correct. Can we just allow the correct arguments to start the pyrsia node?

**Comment by efrisch** [comment]
Will possibly revisit in the future. For now, we can use the `pyrsia config` to update the port in `$HOME/Library/Preferences/rs.pyrsia-cli/pyrsia-cli.toml`. This does work if you have used another port. It's just not as convenient to use as it could be.
