### ISSUE TITLE
Set version on the 0.1 docs and create a new structure for 0.2 and release 0.2 docs as latest

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1175]
Since we now have a 0.2 version ready we need to version our docs to show the 0.2 related documentation.

Follow the steps here to create the appropriate structure - https://docusaurus.io/docs/versioning

**Comment by erwin1** [comment]
I personally think we should remove all out-of-date (0.1) documentation instead of keeping it under 0.1.
I think we need this feature starting from 1.0

**Comment by betarelease** [comment]
We decided to remove the 0.1 documentation since we do not want people to keep on using 0.1 anyway. Better direct them to latest documentation. Hence closing this.
