### ISSUE TITLE
Need a user documentation and contributor documentation section - to separate types of personas engaging with Pyrsia and making it easy for them to find stuff they need.

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1177]

**Comment by betarelease** [comment]
Reference https://docs.ortelius.io/guides/

**Comment by erwin1** [comment]
small note: I tried to start this by having the end-user docs under https://pyrsia.io/docs/tutorials/

the rest is still spread out under https://pyrsia.io/docs/developers/ and https://pyrsia.io/docs/community/get_involved/

**Comment by betarelease** [comment]
We did the minimum required and we can open new issues for further improvements.
