### ISSUE TITLE
Something in build_from_source_docker.md looks outdated

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1179]
### Steps taken/Steps to reproduce

Something in [build_from_source_docker.md](https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_docker.md) looks outdated.

In the Authorize-node-a-as-a-build-node section, the following looks outdated.
```
Enter host:
localhost
Enter port:
7889
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB):
10GB
```

The correct one looks like:
```suggest
Enter host:
localhost
Enter port:
7888
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB):
10 GB
```

### Experienced Instance of the bug

Pyrsia 0.2

**Comment by betarelease** [comment]
This is consistent in the current version - the example shows 7889 and the curl also points to the same port number. Would like to close this if that is ok? @fishseabowl
