### ISSUE TITLE
curl http://boot.pyrsia.link/status returns error

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#1194]
### Steps taken/Steps to reproduce

`curl http://boot.pyrsia.link/status`

returns

`{"errors":[{"code":{"Unknown":""},"message":"channel closed"}]}`

This error prevents nodes from starting.

Attached are the logs from the k8s pyrsia node.

[Uploading prysia-node.txt…]()

### Expected Behavior

Expect peer_addr from curl command

### Experienced Instance of the bug

Pyrsia Version: 0.2.0-rc1

**Comment by fishseabowl** [comment]
Some prysia logs are as follows:
```
 2022-10-13T15:29:19.113Z ERROR pyrsia::build_service::event      > Failed to handle build result for build with ID c249d000-9f3a-409f-aa02-d59d41e88f3e: Failure while adding block to the blockchain: Anyhow Error

Caused by:
    0: Anyhow Error
    1: Connection was closed before a response was received
thread 'tokio-runtime-worker' panicked at 'Connection to peer to be still open.: BlockchainResponse...
......
/home/runner/work/pyrsia/pyrsia/src/network/event_loop.rs:658:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I created issue #1197 to focus on blockchain bugs.

**Comment by betarelease** [comment]
Is this still an issue?

**Comment by betarelease** [comment]
This is a randomly occuring issue. Will close this for now and will open a new one when we know how to reproduce it.
