### ISSUE TITLE
`pyrsia build` still creates new transparency logs for existing docker images

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1199]
### Steps taken/Steps to reproduce

1. Set up nodeA, nodeB and pipeline prototype as [build_from_source_docker.md](https://github.com/pyrsia/pyrsia/blob/main/docs/developers/build_from_source_docker.md).
2. Run  `./target/debug/pyrsia build docker --image alpine:3.16` repeatedly

Result: 
Every time new transparency logs are created and new blocks are added to the blockchain.

### Expected Behavior

`pyrsia build `does not create new transparency logs for existing docker images

### Experienced Instance of the bug

rust version: `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
os: `Mac`
pyrsia version: `0.2`

**Comment by erwin1** [comment]
we've discussed this and concluded the best solution for 0.2 is to ignore p2p build triggers if an artifact already exists in the transparency log.

so the solution would be:
* in handlers.rs in handle_request_build
* before invoking start_build
* use the transparencylog service `get_artifact` method to check if there's a log for the package_type and package_specific_id
* if true. then log something and return
* if false, proceed with the start_build
