### ISSUE TITLE
Run & Test macOS Installer on a fresh machine (Not on developer machine)

### ISSUE THREAD

**Issue by dasmanas** [pyrsia/pyrsia#1201]
### Suggestion details

Run & Test macOS Installer on a fresh machine. It is best to avoid developer machine as developer's machine has so many things already preinstalled. Possible test should run on AWS EC2 MacMini runner. This is will help to find out if the installer requires any prerequisite.

**Comment by dasmanas** [comment]
> I ran it on mac mini with no previous rust installed
> 
> ```
> brew install pyrsia
> ==> Downloading https://brewrepo.pyrsia.io/pyrsia-0.2.0.tar.gz
> ######################################################################## 100.0%
> ==> Installing pyrsia from pyrsia/pyrsia
> Error: Your Xcode (12.4) is too outdated.
> Please update to Xcode 13.4 (or delete it).
> Xcode can be updated from the App Store.
> ```
> 
> having xcode as a prerequisite isn't strange for a developer machine, but why can't 12.4 be enough? (I can't easily upgrade since I really need 12.4 on that machine)

thank you @erwin1. I was expecting this kind of issues. Your comments helped me. Therefore we might need to pour some prerequisite as part of brew install. I am going to run the same on AWS macmini and expecting few more like that.

**Comment by betarelease** [comment]
We will work on this when a real user complains. For now the brew install works as expected. Closing this.
