### ISSUE TITLE
Add brew install docs to quick start guide

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1204]
Since we have a working brew install https://github.com/pyrsia/homebrew-pyrsia now, we should add those instructions to 
 `/docs/tutorials/quick-installation.mdx` as well

**Comment by dasmanas** [comment]
I have similar story https://github.com/pyrsia/pyrsia/issues/1200 tracked under epic https://github.com/pyrsia/pyrsia/issues/1010.

**Comment by betarelease** [comment]
Closing this as duplicate of #1200
