### ISSUE TITLE
Duplicate builds with library/alpine:3.16 and alpine:3.16

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#1216]
We should prepend `library/` to image names that are missing / in the name.  `library/` is the default org if one is not provided fro DockerHub. This will prevent duplicate builds from happening when using library/alpine:3.16 and alpine:3.16.  

The other way to go is to remove `library/`.  Just need consistency.

**Comment by ihcomega56** [comment]
@sbtaylor15 @tiainen I haven't understood build service completely yet, but 

https://github.com/tiainen/pyrsia_build_pipeline_prototype/blob/fdfa3999358cbc51b22c3b4979cbf30ec2fe3977/src/pipeline/build_pipeline.rs#L134-L138

here this logic seems to implement what we want to achieve. Is it related to this task?

**Comment by ihcomega56** [comment]
The goal of this task is adding the same logic to the client side. Changes to be added to not build service but CLI.
