### ISSUE TITLE
Build Node use authenticated account with DockerHub to avoid rate limiting

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#1217]
See [DockerHub Rate Limiting](https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=For%20anonymous%20users%2C%20the%20rate,Enhanced%20Service%20Account%20add%2Don) 

Right now the build node prototype is using anonymous RestApi queries that are rate limited.

**Comment by betarelease** [comment]
This is fixed since we are using a docker account now.
