### ISSUE TITLE
Show useful error messages in the Pyrsia CLI

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1221]
When the Pyrsia CLI receives an error (e.g. http 400 or 500) it should display a better error message when possible.

Example: see #1215 where the build request fails because the artifact is already available ==> the pyrsia CLI should display a meaningful error, so the user does not have to view the logs just to see what is happening.

**Comment by betarelease** [comment]
Once we trigger the build and if the build pipeline returns an error during the build process we just return the 400 error but do not have a callback to retrieve the details of the error.

**Comment by erwin1** [comment]
moving to milestone 0.2.2
