### ISSUE TITLE
Artifact p2p provide should happen before new block broadcast

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1246]
Current situation:

A build node starts a build for a new artifact. When the build succeeds, it follows this procedure:

1. it creates the transparency log for the artifact and uses the transparency log service to add it to the ledger
2. the transparency log service uses the blockchain service to add the log as a payload to a new block
 (this is where the consensus should happen)
3. when the block is added, it is broadcast to connected peers, who store the transparency log in their local log database
4. after this, the log is written to the build node's transparency log database
5. and only after this, the artifact file is provided on the p2p network

The problem with this:

- step 3 is awaits the broadcast of new blocks, so step 4 and 5 only happens when the broadcast is done
- as a result, a peer that receives the block early on, can have a transparency log for a given artifact, but it won't be able to download it because step 5 didn't execute yet

Possible solution:

- the broadcast of new blocks should not block the publication process
- explore better ways for this mechanism to work, and we should include the consensus mechanism in our thinking because this might change the way this works anyway

**Comment by efrisch** [comment]
One recommendation from the libp2p team was implementing the [ping protocol](https://github.com/libp2p/rust-libp2p/blob/master/protocols/ping/src/lib.rs). Which is more of a heartbeat in libp2p. From [here](https://docs.libp2p.io/concepts/fundamentals/protocols/),
"The ping protocol is a simple liveness check that peers can use to quickly see if another peer is online."

**Comment by dasmanas** [comment]
Hey @erwin1 is this issue still relevant? I put together a flow which is currently implemented inside handle build result.

![HandleBuildResult](https://user-images.githubusercontent.com/12514131/215853662-e25950f6-d9aa-47a2-aac7-0164412b6d7b.png)

Link to the diagram: https://lucid.app/lucidchart/ac15c21f-1e25-42bf-b672-2fac99cd1e1b/edit?viewport_loc=-379%2C60%2C2335%2C1095%2C0_0&invitationId=inv_a2ce1aed-a58c-4e92-aeee-9e4d3546925a
