### ISSUE TITLE
Pyrsia CLI should allow to update/set specific pyrsia node parameter (non interactive)

### ISSUE THREAD

**Issue by karolh2000** [pyrsia/pyrsia#1248]
### Suggestion details

Currently, the only way to update the node config is via the `pyrsia config` command which is interactive operation and cannot be used without direct human interaction. We need a way to update the node properties in different environments like scripts/docker/etc. The proposed comments:

`pyrsia config edit host` - update the node host
`pyrsia config edit port` - update the node port
`pyrsia config edit storage` - update the allowed storage

**Comment by dasmanas** [comment]
Duplicate of https://github.com/pyrsia/pyrsia/issues/1131
