### ISSUE TITLE
Integration Tests - tests if docker image can be pulled form pyrsia network

### ISSUE THREAD

**Issue by karolh2000** [pyrsia/pyrsia#1249]
### Suggestion details

Scenario
1) Create node 1 - configured to be authorized + build service
2) Create node 2 - peered with node 1
3) Using node 2 - request adding a new docker image
4) Check if the docker image appears in the transparency log (node 2)
5) Check if the docker image can be pulled from node 2.

**Comment by ihcomega56** [comment]
Implemented in https://github.com/pyrsia/pyrsia-integration-tests/pull/10.
