### ISSUE TITLE
Need a mechanism to determine build's state (based on the build ID)

### ISSUE THREAD

**Issue by karolh2000** [pyrsia/pyrsia#1254]
### Suggestion details

When I submit a request to build docker/maven all I get is:

"Build request successfully handled. Build with ID 5 has been started"

which doesn't provide enough info about the build process. We need mechanism which would tell us the build state:

STARTED, RUNNING, SUCCESSFUL, FAILD, REJECTED, etc

We can check periodically if `inspect-log` has the building artifact data but in case it fails then the logs never have the data. Possibly we need a new CLI functionality to track this use case, e.g:

`pyrsia build docker --image status BUILD_ID`

**Comment by dasmanas** [comment]
It would be also nice to include following information under build status

- PeerIDs currently handling the build
- A streaming option to follow build log of a specified peer . E.g. `pyrsia log --build-id <BUILD_ID> --peer-id <PEER_ID>`
- In future
    - If build is successful, how we reach to consensus to approve.
    - If build is successful, but not reached to consensus. Get the root cause.

**Comment by betarelease** [comment]
https://github.com/pyrsia/pyrsia/pull/1360
