### ISSUE TITLE
Explore: Refactor: use unified mechanism throughout the pyrsia node

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1267]
Currently, the internal Pyrsia components use different mechanisms to communicate asynchronously with each other.

This issue is to explore and refactor the Pyrsia code to use a unified mechanism.

**Comment by erwin1** [comment]
first step: get rid of the Arc<Mutex> between the Transparency Log Service and the Blockchain service  #1347

**Comment by betarelease** [comment]
Confirm if the exploration is completed. Create separate issues for more code that needs refactoring. @erwin1
