### ISSUE TITLE
Running tests modify CLI config settings

### ISSUE THREAD

**Issue by jperedadnr** [pyrsia/pyrsia#1273]
### Steps taken/Steps to reproduce

Remove  ` /Users/$user/Library/Preferences/rs.pyrsia-cli/`, clean/build Pyrsia, and check the configuration, a default configuration is created:

```
$ ./pyrsia config -s
Config file path: /Users/$user/Library/Preferences/rs.pyrsia-cli/default-config.toml
host = 'localhost'
port = '7888'
disk_allocated = '5.84 GB'
```

Modify as needed:
```
$ ./pyrsia config -e
Enter host: 
localhost
Enter port: 
7889
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
10 GB
Node configuration Saved !!
```

Verify it:
```
./pyrsia config -s
Config file path: /Users/$user/Library/Preferences/rs.pyrsia-cli/default-config.toml
host = 'localhost'
port = '7889'
disk_allocated = '10 GB'
```

Now run tests:
```
cargo test --workspace
```

And check the configuration again, it has been changed to the values that are set in `cli/handlers.rs::test_valid_config_edit` test:
```
$ ./pyrsia config -s
Config file path: /Users/$user/Library/Preferences/rs.pyrsia-cli/default-config.toml
host = 'some.localhost'
port = '65535'
disk_allocated = '10 GB'
```

### Expected Behavior

configuration remains the same as it was before running tests.

### Experienced Instance of the bug

rustc 1.63.0 (4b91a6ea7 2022-08-08)
Mac

**Comment by betarelease** [comment]
Related and fixed in #1279
