### ISSUE TITLE
Github action build-osx failed due to Google Cloud Storage permission denied

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1275]
Details:
```
Run .github/workflows/homebrew-installer-upload.sh 0.2.0+2483 latest x86_64
ServiceException: 401 Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist).
Error: Process completed with exit code 1.
```

Link: https://github.com/pyrsia/pyrsia/actions/runs/3429433004/jobs/5715042465#logs

**Comment by dasmanas** [comment]
I can see in the same [workflow](i.e. https://github.com/pyrsia/pyrsia/actions/runs/3429433004/jobs/5715042465#logs) `build-push-linux` is also failing during GCS upload.

**Comment by fishseabowl** [comment]
build-osx fails again on `Publish Build to NIGHTLY GCS repo`. Details are as follows:
```
Building synchronization state...
Starting synchronization...
Copying file://syncdir/index.html [Content-Type=text/html]...
/ [0 files][    0.0 B/ 12.5 KiB]                                                
Copying file://syncdir/latest/index.html [Content-Type=text/html]...
/ [0 files][    0.0 B/ 24.5 KiB]                                                
module 'sys' has no attribute 'maxint'
Copying file://syncdir/latest/x86_64/index.html [Content-Type=text/html]...
/ [0/3 files][ 12.5 KiB/ 89.8 KiB]  13% Done                                    
/ [1/3 files][ 89.8 KiB/ 89.8 KiB]  99% Done                                    
/ [2/3 files][ 89.8 KiB/ 89.8 KiB]  99% Done                                    
/ [3/3 files][ 89.8 KiB/ 89.8 KiB] 100% Done                                    
Operation completed over 3 objects/89.8 KiB.                                     
CommandException: 1 files/objects could not be copied/removed.
Error: Process completed with exit code 1.
```
link: https://github.com/pyrsia/pyrsia/actions/runs/3768325808/jobs/6406664557

**Comment by dasmanas** [comment]
thank you @fishseabowl. I will work on this. The behavior is little wired to me. Even though it is said all the 3 required files has been synced but then it complains. Even when I am trying to replicate the same from local it works perfectly fine. Makes it even difficult to figuring out the issue.

**Comment by dasmanas** [comment]
Compiled CRCMOD is not installed in GitHub macos runner. This is one major difference from local to github runner.

Run https://github.com/pyrsia/pyrsia/actions/runs/3790545591/jobs/6445243602 without installing CRCMOD separately. Going with default gsutil installation provided for GitHub action.
`gsutil version -l` shows `compiled crcmod: False`

Run https://github.com/pyrsia/pyrsia/actions/runs/3790737763/jobs/6445597380 while installing CRCMOD explicitly.
`gsutil version -l` shows `compiled crcmod: True`


### OVERVIEW
  Google Cloud Storage provides a cyclic redundancy check (CRC) header that
  allows clients to verify the integrity of object contents. For non-composite
  objects Google Cloud Storage also provides an MD5 header to allow clients to
  verify object integrity, but for composite objects only the CRC is available.
  gsutil automatically performs integrity checks on all uploads and downloads.
  Additionally, you can use the ``gsutil hash`` command to calculate a CRC for
  any local file.

  The CRC variant used by Google Cloud Storage is called CRC32C (Castagnoli),
  which is not available in the standard Python distribution. The implementation
  of CRC32C used by gsutil is provided by a third-party Python module called
  `crcmod <https://pypi.python.org/pypi/crcmod>`_.

  The crcmod module contains a pure-Python implementation of CRC32C, but using
  it results in very poor performance. A Python C extension is also provided by
  crcmod, which requires compiling into a binary module for use. gsutil ships
  with a precompiled crcmod C extension for macOS; for other platforms, see
  the installation instructions below.

  At the end of each copy operation, the ``gsutil cp`` and ``gsutil rsync``
  commands validate that the checksum of the source file/object matches the
  checksum of the destination file/object. If the checksums do not match,
  gsutil will delete the invalid copy and print a warning message. This very
  rarely happens, but if it does, please contact gs-team@google.com.

**Comment by dasmanas** [comment]
Analysis was correct. Due to missing precompiled CRCMOD in google-github-actions/setup-gcloud the client was not able to verify the integrity of the transferred object to Cloud bucket.

Evidence of successful run: [build-osx](https://github.com/pyrsia/pyrsia/actions/runs/3796102592/jobs/6456060420) run and step **_Publish Build to NIGHTLY GCS repo_**
