### ISSUE TITLE
Pyrsia Microsoft VS Code IDE Extension

### ISSUE THREAD

**Issue by karolh2000** [pyrsia/pyrsia#1291]
### Suggestion details

Doc link: https://docs.google.com/document/d/1w2BuJaDLiK7--Ecr77vybCyTb3KfJru_uNZOAZCNffE/edit?usp=sharing

Summary:
Overview
The main goal of the extension is to simplify operations related to Pyrsia and Pyrsia nodes. The targeted platform is Microsoft Visual Studio Code as one of the most popular and free IDE currently available.

Functionality
Pyrsia Installation
- The pyrsia binaries (node/CLI) installed along the extension.

Node
 - Configure the node
 - Start/Stop the node
 - View the node’s log 
 - Monitor the node status (health)
 - Transparency log

View the transparency log for the fetch/used binaries.
 - Security Information
 - View the security info for the dependencies

Build Service
 - Upload/add a binary to the Pyrsia network
 - Check/Track the build progress

Architecture
TBD
UI and Design
TBD
Publishing and Distributing the Extension
The extension will be hosted and distributed via the MS VS Code extension store. More information: [Publishing Extensions | Visual Studio Code Extension API](https://code.visualstudio.com/api/working-with-extensions/publishing-extension)

**Comment by betarelease** [comment]
prototype work started here #1400

**Comment by karolh2000** [comment]
Done, more info: https://github.com/pyrsia/pyrsia-vscode-extension
