### ISSUE TITLE
Unable to configure disk space with decimals

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1308]
### Steps taken/Steps to reproduce

Tried configuring disk space with decimals, without success.
```
xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia config -e                               
Enter host: 
localhost
Enter port: 
7889
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
0.1 GB
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
1.1 GB
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
0.15 GB
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
5.84 GB
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
5 GB
Node configuration Saved !!
```

### Expected Behavior

Allow to configure disk space with decimals

### Experienced Instance of the bug

Rust version: rustc 1.63.0 (4b91a6ea7 2022-08-08)
OS: Mac OS
Pyrsia version: commit ce8eb66838c31bd00b1aa178c0d0003a3a73412c

**Comment by betarelease** [comment]
This is not a bug. This is expected behavior. We only need to support whole number disk sizes and only sizes that are GB or more. Anything more granular than a whole number is not supported on Pyrsia.

**Comment by fishseabowl** [comment]
@betarelease I agree with you. Maybe we should change the default disk allocation value of 5.84 GB to an integer and show in the prompt that only integers are supported, otherwise it would be confusing.
https://github.com/pyrsia/pyrsia/blob/bc921f645a4a076132b7c18971424029bf02263c/src/cli_commands/config.rs#L32-L40

**Comment by erwin1** [comment]
Yes, let's change the default to 10 GB -  see also PR #1311

**Comment by dasmanas** [comment]
> Yes, let's change the default to 10 GB - see also PR #1311

Changed through PR https://github.com/pyrsia/pyrsia/pull/1309 as in this PR diskspace validation is also getting changed.
