### ISSUE TITLE
Need a review of docs/community/get_involved/local_dev_setup.md and update the docs

### ISSUE THREAD

**Issue by dasmanas** [pyrsia/pyrsia#1319]
### Steps taken/Steps to reproduce

Need a review [docs/community/get_involved/local_dev_setup.md](https://github.com/pyrsia/pyrsia/pull/1309/files/43943229488e5f36d29d856d80a3bd248f35d713#diff-e14aa72813a5627040c989289257499ca46cf8614a6316b0eac6ec10e21c001b)

Is the output of `pyrsia -s` still valid?

```
 $ ./pyrsia -s
    Connected Peers Count:       1
    Artifacts Count:             3 {"manifests": 1, "blobs": 2}
    Total Disk Space Allocated:  5.84 GB
    Total Disk Space Allocated:  10 GB
    Disk Space Used:             0.0002%
```

### Experienced Instance of the bug

rustc 1.63.0

**Comment by dgarus** [comment]
@dasmanas Hi!
In the `Simulate a network` section: 

> Download or clone the prototype repo and run as follows (jq must be installed locally before)

And what should I get? Why do I need to do this step?

**Comment by dasmanas** [comment]
> @dasmanas Hi! In the `Simulate a network` section:
> 
> > Download or clone the prototype repo and run as follows (jq must be installed locally before)
> 
> And what should I get? Why do I need to do this step?

Pyrsia's build pipeline code is kept in a separate git repo `https://github.com/tiainen/pyrsia_build_pipeline_prototype.git`. Download from here and follow the remaining steps
```
cd pyrsia_build_pipeline_prototype
RUST_LOG=debug cargo run
```
The above will help you to run Build Pipeliine. Authorize need interacts to BuildPipeline to build.
