### ISSUE TITLE
Create a "test matrix" to see where we stand from an end user perspective. Be able to show folks what is happening with our testing. (see if Ayana can help with this)

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1328]
​

**Comment by betarelease** [comment]
Created by sudhindrar for Steve Taylor
  See the dashboard of [sudhindrar’s Team](https://action.parabol.co/team/Zr7KiRsaCj)

  *Powered by [Parabol](https://www.parabol.co/integrations/github)*

**Comment by betarelease** [comment]
Yes this is what I had in mind. As we cover more areas we should continue to update this page so that we/community knows how much testing goes into Pyrsia.

**Comment by ihcomega56** [comment]
@betarelease Thank you for reviewing it! It got merged.
