### ISSUE TITLE
Starting pyrsia_node fails when creating a DocumentStore without an index

### ISSUE THREAD

**Issue by johanvos** [pyrsia/pyrsia#133]
When starting the pyrsia_node, a DocumentStore is created with an empty set of indexes. This is forbidden by the document_store implementation, hence the process panics with
```
thread 'main' panicked at 'Failed to create DocumentStore: Custom("At least one index specification is required when creating a DocumentStore.")', pyrsia_node/src/main.rs:73:53
```

**Comment by prince-chrismc** [comment]
Just testing new automation dont mind me 🙈
