### ISSUE TITLE
Use a fixed rust toolchain

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1352]
This is related to #1288 but not the same.

As it turns out, we are NOT using a fixed toolchain version, so we have been using the version that github provided by default.
This is also the reason clippy started to fail in #1326 (fixed in #1341)

So the first step, before upgrading to 1.65.0 in #1288 is to allow our workflows to use a fixed toolchain version.

**Comment by betarelease** [comment]
Toolchain specification
Standard release channel toolchain names have the following form:


<channel>[-<date>][-<host>]

<channel>       = stable|beta|nightly|<major.minor>|<major.minor.patch>
<date>          = YYYY-MM-DD
<host>          = <target-triple>





- name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

**Comment by betarelease** [comment]
Also in the cargo.toml we can now specify rust-version for the package

https://doc.rust-lang.org/cargo/reference/manifest.html due to this RFC - https://github.com/rust-lang/rfcs/pull/1953 So that would be the way to go and specify `major.minor`

**Comment by betarelease** [comment]
https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

**Comment by erwin1** [comment]
it will be key to find all places where we use rust tools

e.g. there's this line in `installers/docker/CodeCoverage.Dockerfile`
```
FROM rust:1.57.0-buster
```
