### ISSUE TITLE
Github action: Rust / docker (push) error

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1355]
Rust / docker (push) error: incorrect username or password. The details are as follows:
```
Run docker/login-action@v2
  with:
    username: ***
    password: ***
    ecr: auto
    logout: true
  env:
    CARGO_TERM_COLOR: always
Logging into Docker Hub...
Error: Error response from daemon: Get "https://registry-1.docker.io/v[2](https://github.com/pyrsia/pyrsia/actions/runs/3588356818/jobs/6042392002#step:3:2)/": unauthorized: incorrect username or password
```
Link: https://github.com/pyrsia/pyrsia/actions/runs/3588356818/jobs/6042392002

**Comment by betarelease** [comment]
I know why this happened. I had to do forgot password to get the password for our docker account so it might need to be changed in such places. Will do that tomorrow morning.

**Comment by betarelease** [comment]
updated password in settings and re-ran workflow. This is now fixed.
