### ISSUE TITLE
Integration Tests - Could not find `protoc` installation and this build crate cannot proceed without...

### ISSUE THREAD

**Issue by karolh2000** [pyrsia/pyrsia#1368]
### Steps taken/Steps to reproduce

Broken integration tests: https://github.com/pyrsia/pyrsia-integration-tests/actions/runs/3602759995/jobs/6072091639#step:6:65

### Experienced Instance of the bug

N/A
N/A
N/A

**Comment by karolh2000** [comment]
PR - https://github.com/pyrsia/pyrsia-integration-tests/pull/21

**Comment by betarelease** [comment]
This is merged with the PR above. Closing this
