### ISSUE TITLE
Integration tests - Notify the result to Slack

### ISSUE THREAD

**Issue by ihcomega56** [pyrsia/pyrsia#1373]
## Goal
Report the result of integration tests to Slack.

## Current issue to be solved
https://github.com/pyrsia/pyrsia-integration-tests runs twice a day regularly, but the result is not notified to the team.

**Comment by betarelease** [comment]
This is done right @ihcomega56. We should close?

**Comment by ihcomega56** [comment]
Sure. Thanks.
