### ISSUE TITLE
Custom pyrsia/rust-toolchain GitHub action installs old version of yq

### ISSUE THREAD

**Issue by tiainen** [pyrsia/pyrsia#1377]
The [new GitHub action](https://github.com/pyrsia/rust-toolchain) for setting up the necessary tools for building Pyrsia, installs an older version of `yq` by using the `pip` installer: https://github.com/pyrsia/rust-toolchain/blob/5820c81/action.yml#L17. At the time of writing, it installs version `3.1.0` (https://pypi.org/project/yq/).

This causes issues later on in the rest of the GitHub workflow, where version 4 of `yq` is implied: https://github.com/pyrsia/pyrsia/blob/d0196a6/.github/workflows/rust.yml#L258-L261

The action fails with the following error:

```
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.image.tag |= "0.2.1-2606"': [Errno 2] No such file or directory: '.image.tag |= "0.2.1-2606"'
Error: Process completed with exit code 2.
```

**Comment by tiainen** [comment]
@sbtaylor15 `rust-toolchain` should also install version 4 of `yq` by using `go install` instead of using the `pip3` installer?

**Comment by fishseabowl** [comment]
Reference link: https://github.com/pyrsia/pyrsia/actions/runs/3637166541/jobs/6137883481

**Comment by sbtaylor15** [comment]
Removed yq from action and replaced with npm install toml-cil which converts a toml file to json.  Then using jq to parse.  Update made in the [rust-toolchain repo](https://github.com/pyrsia/rust-toolchain) commit [#7fea98d](https://github.com/pyrsia/rust-toolchain/commit/57d3ebacb020215d14023110536b704c6)
