### ISSUE TITLE
Define "the block"

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#138]
It's time for the team to get very serious about what is going to go in this block - at least for a phase 1. I will work to get some concensus from the team and a block structure together

**Comment by fishseabowl** [comment]
I think: At the beginning, 
1. just for simplified consensus algorithm,  only one commit node be supported. This means only this commit node could add the new block to the existing blockchain. 
2. blockchain fork is not supported. 
3. Block finality is deterministic, not probabilistic.
Welcome any input

**Comment by mgrand** [comment]
@fishseabowl I agree that those three are good principles to follow for now. Since there will be only one commit node, we should look into hosting the commit node on Google cloud so that it can be highly available.
