### ISSUE TITLE
Pyrsia network with multiple authority nodes - with light consensus

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1395]

**Comment by erwin1** [comment]
I misread the description of this issue and it shouldn't be part of #1276

Instead, I think the current staging version of the code is already capable of doing this, but this must be verified/tested.

**Comment by betarelease** [comment]
with 0.2.4 deployed were you able to verify this behaviour @fishseabowl ?

**Comment by fishseabowl** [comment]
0.2.4 currently supports multiple authority nodes. For details, please refer to the command `pyrsia authorize --peer <PEER_ID>`
