### ISSUE TITLE
Release v0.2.2

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#1432]
## Before tagging the release in github

- [x] Check and make sure the version in Cargo.toml and rust.yml is correct in the main branch
- [x] Run the [integration tests](https://github.com/pyrsia/pyrsia-integration-tests/actions) on the main branch and record the output in the comments of the release issue. Ensure there are no failures - also ensure there is no flakiness observed.
- [x] Run [manual confidence tests](/docs/developers/prerelease_manual_tests.md) using a local build from the main branch

## Tagging the release

Once all the above steps are completed and verified to be success, start the release procedure:

- [x] Go the [GitHub releases](https://github.com/pyrsia/pyrsia/releases) and [Draft a new release](https://github.com/pyrsia/pyrsia/releases/new)
- [x] Select target branch `main`
- [x] Click Choose a tag and type the tagname starting with a `v` e.g. `v0.2.2` - select "Create new tag on publish"
- [x] Name the release: start with the tag, but make sure the title already includes a quick summary of the most important change(s)
- [x] Click generate release notes. This will generate the technical release notes of all changes.
- [x] Summarize the changes in a more readable list above the technical release notes - see [0.2.1 as an example](https://github.com/pyrsia/pyrsia/releases/tag/v0.2.1)
- [x] Check the box for 'Set a pre-release' (for now)
- [x] Make sure 'Set as latest release' is NOT checked (for now)
- [x] Hit "Publish release" and wait for the workflow to finish

## Testing the release

- [x] Deploy to nightly cluster
- [x] Run installers + manual confidence tests connecting to nightly
  - [x] Linux
  - [x] MacOS
  - [x] Windows
  - [x] Docker

## Deployment

- [x] Make sure apt repo and [brew repo](https://github.com/pyrsia/homebrew-pyrsia) contain the correct latest release
- [x] Upload windows MSI to github release
- [x] Deploy the production authorized nodes with this release
- [x] Run installers + [manual confidence tests](/docs/developers/postrelease_manual_tests.md) connecting to production
  - [x] Linux
  - [x] MacOS
  - [x] Windows
  - [x] Docker

## Post-release

- [x] Edit the [GitHub release](https://github.com/pyrsia/pyrsia/releases) and uncheck 'Set as pre-release' and check 'Set as latest release'.
- [x] Update documentation to point to the latest released version
- [x] Update the version number to prepare for the next release
  - [x] Make sure you update the version in `Cargo.toml`
  - [x] Update github actions with the new version number eg. <https://github.com/pyrsia/pyrsia/pull/1349/files>
  - [x] Create a PR with the version change and run it through the github actions to ensure nothing fails.
  - [x] Verify that the rust toolchain version is set to the version we would like to release this version. Since 0.2.2 this is captured in one place - at the top of `Cargo.toml`
  - [x] Merge the PR to the main branch

## Outreach

- [x] Add a blog to promote this release - like <https://pyrsia.io/blog/2022/11/30/pyrsia-0.2.1-released/>

**Comment by erwin1** [comment]
```
Starting Pyrsia integration tests in ....
pyrsia_cli.bats

Setting up the test environment...
INFO : Integration tests are running using this version of Pyrsia: 15d3225 prepare 0.2.2 release
INFO : For more details, refer to https://github.com/pyrsia/pyrsia/commit/15d3225 (This link works properly only when you test pyrsia/pyrsia repository.)
Building the Pyrsia CLI sources (Pyrsia CLI source dir: /tmp/pyrsia_tests/pyrsia), it might take a while...
Building Pyrsia CLI completed!
Building the Pyrsia node docker image and starting the container, it might take a while...
The Docker Pyrsia node container is up!
The tests environment is ready!
Running tests...
 ✓ Testing 'pyrsia help' CLI, check if the help is shown.
 ✓ Testing 'pyrsia ping' CLI, check if the node is up and reachable.
 ✓ Testing 'pyrsia status' CLI, check if the node is connected to peers.
 ✓ Testing 'pyrsia list' CLI, check if the node returns the list of peers.
 ✓ Testing 'pyrsia config' CLI, check if the config can be changed and shown.
 ✓ Testing 'pyrsia config edit' CLI, check if input values are validated.
 ✓ Testing 'pyrsia version', check if the CLI version shows.
 ✓ Testing 'pyrsia build' help options, check if the build help is shown.
 ✓ Testing 'pyrsia inspect-log' help/options, check if the inspect-log help is shown.
 ✓ Testing 'pyrsia authorize' help/options, check if the authorize help is shown.

Tearing down the tests environment...
Cleaning up the docker images and containers...
Done tearing the tests environment!
pyrsia_node_docker_build_service.bats

Setting up the test environment...
INFO : Integration tests are running using this version of Pyrsia: 15d3225 prepare 0.2.2 release
INFO : For more details, refer to https://github.com/pyrsia/pyrsia/commit/15d3225 (This link works properly only when you test pyrsia/pyrsia repository.)
Building the Pyrsia CLI sources (Pyrsia CLI source dir: /tmp/pyrsia_tests/pyrsia), it might take a while...
Building Pyrsia CLI completed!
Building the Pyrsia node docker image and starting the container, it might take a while...
The Docker Pyrsia node container is up!
The tests environment is ready!
Running tests...
 ✓ Testing the build service, docker (build and download docker image, inspect-log).
	- Building docker image alpine:3.16 - [/tmp/pyrsia_tests/pyrsia/target/release/pyrsia build docker --image alpine:3.16], it might take a while...
	- Docker image built successfully - alpine:3.16
 ✓ Verify that a node can't be authorized twice.
 ✓ Verify that a build starts if an artifact is requested but doesn't exist in the transparency log yet.

Tearing down the tests environment...
Cleaning up the docker images and containers...
Done tearing the tests environment!

13 tests, 0 failures
```

**Comment by erwin1** [comment]
@dasmanas I was having an issue with `Make sure [brew repo](https://github.com/pyrsia/homebrew-pyrsia) contains the correct latest release` 

https://brewrepo.pyrsia.io/stable/x86_64/ doesn't contain the latest release, so I wonder if I missed something or something went wrong. 
In the diagram you say 'GitHub Action - Push release archive'  but where is that and how is it triggered?

**Comment by sbtaylor15** [comment]
Installed from apt-get repo onto the nightly GCP VM without any errors.  Also, ran a set of builds without errors.  Images included in build were: ubuntu, debian, nginx, openjdk

**Comment by dasmanas** [comment]
> @dasmanas I was having an issue with `Make sure [brew repo](https://github.com/pyrsia/homebrew-pyrsia) contains the correct latest release`
> 
> https://brewrepo.pyrsia.io/stable/x86_64/ doesn't contain the latest release, so I wonder if I missed something or something went wrong. In the diagram you say 'GitHub Action - Push release archive' but where is that and how is it triggered?
> 
> and one extra question: is there a way I can test the brew install without actually publishing it (or at least without making it the default latest version). the reason is we want to do some manual checks connecting to nightly before actually opening it up.

Identified an issue while publishing it in the repo. This needs to be fixed. The archives are available under https://console.cloud.google.com/storage/browser/homebrewrepo/stable/x86_64?project=pyrsia-sandbox. And https://brewrepo.pyrsia.io/ is gateway to the google bucket named `homebrewrepo`. Created an issue

Release is not impacted by this issue. Even though the listing of archives are not available under https://brewrepo.pyrsia.io/stable/x86_64/ but archive https://brewrepo.pyrsia.io/stable/x86_64/pyrsia-0.2.2+2699.tar.gz is accessible to download.

**Comment by erwin1** [comment]
created #1445 to deal with the rust update
