### ISSUE TITLE
Pin GH Action Runners instead of windows-latest & macos-latest

### ISSUE THREAD

**Issue by dasmanas** [pyrsia/pyrsia#1434]
### Suggestion details

We should also consider pinning windows version & macos version respectively instead of `runs-on: windows-latest` & `runs-on: macos-latest` like we did in https://github.com/pyrsia/pyrsia/issues/1428 for ubuntu runner. Instead of using latest, we need to pin specific version.

**Comment by sbtaylor15** [comment]
macos-latest = macos-12
windows-latest = windows-2022
