### ISSUE TITLE
Github action .github/workflows/build.sh reports an error

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1466]
Details are as follows:
```
Run .github/workflows/build.sh
error: no such subcommand: `remove`

	Did you mean `report`?
Error: Process completed with exit code [10](https://github.com/pyrsia/pyrsia/actions/runs/3809065416/jobs/6480154412#step:7:11)1.
```
Link: https://github.com/pyrsia/pyrsia/actions/runs/3809065416/jobs/6480154412

**Comment by fishseabowl** [comment]
@efrisch I think this is related to your PR #1464. https://github.com/pyrsia/pyrsia/blob/2f1c3253bf968ca55f1944259e487f1eea3448f2/.github/workflows/build.sh#L18
Could you please look into it. Thanks

**Comment by sbtaylor15** [comment]
Latest commits to PR #1464 fix this issue.  Closing
