### ISSUE TITLE
rust-lint and rust-lint-skipped should have the same paths and steps

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#1470]
Inconsistent paths and steps are causing the GitHub Checks to fail.

**Comment by dasmanas** [comment]
<img width="1514" alt="Screenshot 2023-01-04 at 3 38 31 PM" src="https://user-images.githubusercontent.com/12514131/210670267-0d14448f-5939-4ca1-aa84-1d28471f68db.png">

**Comment by betarelease** [comment]
https://github.com/pyrsia/pyrsia/pull/1473
