### ISSUE TITLE
Tag and Release - 0.2.3 version of Pyrsia

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#1493]
## Before tagging the release in github

- [x] Check and make sure the version in Cargo.toml and rust.yml is correct in the main branch
- [x] Run the [integration tests](https://github.com/pyrsia/pyrsia-integration-tests/actions) on the main branch and record the output in the comments of the release issue. Ensure there are no failures - also ensure there is no flakiness observed.
- [x] Run [manual confidence tests](https://pyrsia.io/docs/developers/prerelease_manual_tests) using a local build from the main branch
  - [x] macOS 
    - [x] Authorize Node
    - [x] Peer Node
    - [x] Build Node
  - [x] Windows
    - [x] Peer Node i.e. end user testing only
  - [x] Linux(Ubuntu-20.04.5 LTS)
    - [x] Authorize Node
    - [x] Peer Node
    - [x] Build Node
  - [x] Docker
    - [x] Peer Node i.e. end user testing only
> :warning: **Terminal C** Go to the build pipeline prototype repo and run: Statement is not clear. Repo https://github.com/tiainen/pyrsia_build_pipeline_prototype is not part of Pyrsia org.

## Tagging the release

Once all the above steps are completed and verified to be success, start the release procedure:

- [x] Go the [GitHub releases](https://github.com/pyrsia/pyrsia/releases) and [Draft a new release](https://github.com/pyrsia/pyrsia/releases/new)
- [x] Select target branch `main`
- [x] Click Choose a tag and type the tagname starting with a `v` e.g. `v0.2.2` - select "Create new tag on publish"
- [x] Name the release: start with the tag, but make sure the title already includes a quick summary of the most important change(s)
- [x] Click generate release notes. This will generate the technical release notes of all changes.
- [x] Summarize the changes in a more readable list above the technical release notes - see [0.2.1 as an example](https://github.com/pyrsia/pyrsia/releases/tag/v0.2.1)
- [x] Check the box for 'Set as pre-release' (for now)
- [x] Make sure 'Set as latest release' is NOT checked (for now)
- [x] Hit "Publish release" and wait for the workflow to finish

## Nightly release

- [x] Deploy to nightly cluster - Refer https://pyrsia.io/docs/sre/kubernetes-helm/
- [x] Test nightly release
  - [x] Run installers + manual confidence tests connecting to nightly
    - [x] Linux - install latest stable release till #1509 is not closed ❌ 
    ```
    # workaround
    sudo apt-get update
    sudo apt-get install -y wget gnupg
    sudo wget -q -O - https://repo.pyrsia.io/repos/Release.key |  gpg --dearmor  > pyrsia.gpg
    sudo install -o root -g root -m 644 pyrsia.gpg /etc/apt/trusted.gpg.d/
    rm pyrsia.gpg
    sudo su
    echo "deb https://repo.pyrsia.io/repos/stable focal main" >> /etc/apt/sources.list
    exit
    sudo apt-get update
    sudo apt-get install -y pyrsia

    # Some edits need to make to connect to nightly cluster.
    # Edits to set bootstrap-url nightly-cluster
    sudo sed -i '/ExecStart=/ s/$/ --bootstrap-url http:\/\/boot.nightly.pyrsia.link\/status/' $(sudo find /etc -name pyrsia.service)

    # reload & restart
    systemctl daemon-reload
    service pyrsia restart
    ```
    - [x] MacOS
    - [x] Windows - End user testing only
    - [x] Docker - End user testing only

## Deployment

- [x] Make sure [apt repo](https://repo.pyrsia.io/repos/nightly/pool/main/p/pyrsia/) and [brew repo](https://brewrepo.pyrsia.io/) contain the correct stable release version.
- [x] Upload windows MSI to github release
- [x] Deploy the production authorized nodes with this release - Refer https://pyrsia.io/docs/sre/kubernetes-helm/
- [x] Run installers + [manual confidence tests](/docs/developers/postrelease_manual_tests.md) connecting to production
  - [x] Linux
  - [x] MacOS
  - [X] Windows - _To trigger build, wait for transparency logs to be downloaded completely to the peer node._
  - [x] Docker

## Post-release

- [x] Edit the [GitHub release](https://github.com/pyrsia/pyrsia/releases) and uncheck 'Set as pre-release' and check 'Set as latest release'.
- [ ] Update documentation to point to the latest released version - which doc❓
- [x] Update the version number to prepare for the next release
  - [x] Make sure you update the version in `Cargo.toml`
  - [x] Update github actions with the new version number eg. <https://github.com/pyrsia/pyrsia/pull/1349/files> ❌ - not required any more
  - [x] Create a PR with the version change and run it through the github actions to ensure nothing fails.
  - [x] Verify that the rust toolchain version is set to the version we would like to release this version. Since 0.2.2 this is captured in one place - at the top of `Cargo.toml`
  - [x] Merge the PR to the main branch

## Outreach

- [x] Add a blog to promote this release - like <https://pyrsia.io/blog/2022/11/30/pyrsia-0.2.1-released/>

**Comment by betarelease** [comment]
Release should use this git hash - b0dc62c29fbabaab6af6408d1879ef4d03ff5696

**Comment by dasmanas** [comment]
Clean Integration test run - https://github.com/pyrsia/pyrsia-integration-tests/actions/runs/3884539393/jobs/6635049779

**Comment by dasmanas** [comment]
> ⚠️  https://winrepo.pyrsia.io/ returns empty welcome page.

**Comment by dasmanas** [comment]
Latest installer found for
Apt - [pyrsia_0.2.3+2805_amd64.deb](https://repo.pyrsia.io/repos/stable/pool/main/p/pyrsia/pyrsia_0.2.3%2B2805_amd64.deb)
Brew - [pyrsia-0.2.3+2805.tar.gz](https://brewrepo.pyrsia.io/stable/x86_64/pyrsia-0.2.3%2B2805.tar.gz)
Docker - [0.2.3-2805](https://hub.docker.com/layers/pyrsiaoss/pyrsia-node/0.2.3-2805/images/sha256-91b5409deba22d12215ea2bf842bf289002543a054d5207bc6aae2f4966ce4f0?context=explore)

**Comment by dasmanas** [comment]
[1509](https://github.com/pyrsia/pyrsia/issues/1509)

**Comment by erwin1** [comment]
One last thing: this issue wasn't closed and the milestone was left open. I'll add that to the checklist.
