### ISSUE TITLE
Implement the get_authorized_nodes method to return a list of PeerIDs to enable communication between different auth nodes

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1523]
Currently in src/transparency_log/log.rs, there is a method get_authorized_nodes() that returns a Vec<TransparencyLog>. Perhaps we need another similar method that returns a list of PeerIDs to enable communication between different auth nodes.

**Comment by tiainen** [comment]
It would be better to just change the current method to directly return the `PeerId` instead of the entire transparency log.
