### ISSUE TITLE
openssf: Project Charter

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#157]
Need a project charter that is in line with the OpenSSF charter.  Also, need to determine where the charter.md would live.  Not sure if the .github repo will share it across all repos in the org.

**Comment by prince-chrismc** [comment]
`charter.md` is not a standard file so it wont be shared.

We can put it in .github and link to it from one of the standard files that are shared, does that work too?

**Comment by sbtaylor15** [comment]
I think we can make the bootstrap governance doc work for now.  Closing this issue.  OpenSSF may require a charter down the road.
