### ISSUE TITLE
Repeatedly adding the same node

### ISSUE THREAD

**Issue by dgarus** [pyrsia/pyrsia#1581]
### Steps taken/Steps to reproduce

Adding the same node_id repeatedly is still ok.
Reproducer can be found [here](https://github.com/pyrsia/pyrsia/pull/1538#discussion_r1094935808).

### Expected Behavior

 By design, if an authority node is already in the Pyrsia network and has not been removed, we will not add it again to prevent committing useless blocks.

### Experienced Instance of the bug

rustc 1.66.1 (90743e729 2023-01-10)
Mac OS
v0.2.3

**Comment by fishseabowl** [comment]
@dgarus In addition to duplicate additions, perhaps duplicate remove should be avoided. This means that if an authority node is removed and not added again, it should not be removed again.
