### ISSUE TITLE
The output of the command `./pyrsia inspect-log docker --help` is incorrect

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1603]
### Steps taken/Steps to reproduce

Run `./pyrsia inspect-log docker --help`, the output is as follows:
```
xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia inspect-log docker --help                                       
Show transparency logs for a Docker image

Usage: pyrsia inspect-log docker [OPTIONS] --image <IMAGE>

Options:
      --image <IMAGE>    The docker image (e.g. alpine:3.15.3 or alpine@sha256:1e014f84205d569a5cc3be4e108ca614055f7e21d11928946113ab3f36054801
      --format <FORMAT>  The output format [default: json] [possible values: json, csv]
      --fields <FIELDS>  The list of output fields separated by comma ','.
                         Available fields:
                         	- field: 'Id',	description: TransparencyLog record identity
                         	- field: 'PackageType',	description: Package type (maven, docker and so on)
                         	- field: 'PackageSpecificId',	description: Package specific identity
                         	- field: 'NumArtifacts',	description: Number of artifacts
                         	- field: 'PackageSpecificArtifactId',	description: Package specific artifact identity
                         	- field: 'ArtifactHash',	description: Artifact hash
                         	- field: 'SourceHash',	description: Source hash
                         	- field: 'ArtifactId',	description: Artifact identity
                         	- field: 'SourceId',	description: Source identity
                         	- field: 'Timestamp',	description: Timestamp
                         	- field: 'Operation',	description: Operation (AddArtifact, RemoveArtifact, AddNode, RemoveNode)
                         	- field: 'NodeId',	description: Peer node identity
                         	- field: 'NodePublicKey',	description: Node public key
                         
  -h, --help             Print help
```

### Expected Behavior

1. `--image <IMAGE>` should not be included in `Options`
2. In `-field: 'Id'`: `Id` is an invalid value, the correct value may be `id`
3. In `-field: 'PackageType'`: `PackageType` is an invalid value
4. In `-field: 'PackageSpecificId'`: `PackageSpecificId` is an invalid value
5. In `-field: 'NumArtifacts'`: `NumArtifacts` is an invalid value
6. In `-field: 'PackageSpecificArtifactId'`: `PackageSpecificArtifactId` is an invalid value
7. In `-field: 'ArtifactHash'`: `ArtifactHash` is an invalid value
8. In `-field: 'SourceHash'`: `SourceHash` is an invalid value
9. In `-field: 'ArtifactId'`: `ArtifactId` is an invalid value
10. In `-field: 'SourceId'`: `SourceId` is an invalid value
11. In `-field: 'Timestamp'`: `Timestamp` is an invalid value, the correct value may be `timestamp`
12. In `-field: 'Operation'`: `Operation` is an invalid value
13. In `-field: 'NodeId'`: `NodeId` is an invalid value
14. In `-field: 'NodePublicKey'`: `NodePublicKey` is an invalid value

### Experienced Instance of the bug

Rust version: rustc 1.66.1 (90743e729 2023-01-10)
OS: Mac OS
Pyrsia version: commit b0116a3a94b57d14d01257d6ad61105aee63e05e

**Comment by fishseabowl** [comment]
@dgarus Could you help to have a look at this and issue #1604 if possible? Thanks

**Comment by dgarus** [comment]
> @dgarus Could you help to have a look at this and issue #1604 if possible? Thanks

OMG! Sure.

**Comment by dgarus** [comment]
> --image <IMAGE> should not be included in Options

```
.required(true)
```

I'm not confident, but this looks like a bug in `clap` lib.
