### ISSUE TITLE
Capture Manifests on the node.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#162]
Capture docker manifests as artifacts, create metadata that identifies manifest artifacts and allow the manifests to be retrieved by the docker integration and shared with the Pyrsia network. This will involve these subtasks:

- [x] #171
- [x] #176
- [x] #212
- [x] #213
- [ ] #214
- [ ] #215

This is nice to have but not required for demo

**Comment by prince-chrismc** [comment]
I was under the impression this was already supported? 🤔 

https://github.com/pyrsia/pyrsia/blob/fbe7fb1b6e09adaaab9e7df90c3d2311f2e9915a/pyrsia_node/src/docker/v2/handlers/manifests.rs#L68

Perhaps "capture" does not mean working/saving? That's my understanding

**Comment by erwin1** [comment]
I created #268 to store docker manifests in the artifact manager when we do a pull-through of docker images.

**Comment by betarelease** [comment]
Closing this since #268 should handle what is relevant and for other things we should have more current thinking and create new tickets.
