### ISSUE TITLE
At first to be consistent with other modules, using ed25519 keypair to sign and verify. Change signature struct.

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#185]
Initially, the blockchain supports ed25519 signature algorithm. 
Reason:
1. Reuse ed25519 keypair created in pyrsia_node main.rs
2. NIST endorse EdDSA as digital signature standard. https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf

**Comment by mgrand** [comment]
@fishseabowl Why do we want to use ed25519? I understand from @efrisch that RSA is more quantum resistant, which I the reason I implemented signatures using RSA.

**Comment by fishseabowl** [comment]
Ed25519 Keypair is used at pyrsia/pyrsia_node/src/main.rs 109: let local_key = identity::Keypair::generate_ed25519(); Blockchain module just reuse this keypair. RSA and Secp256k1 keypair would be supported later.

**Comment by prince-chrismc** [comment]
This is an excellent idea! 🚀 
Every node should use 1 one, that will make out setup easier!

***

> RSA is more quantum resistant

Even if thats's true, it still mathematically trivial to solve 🤷 

***

For those in the standup who asked for more context

- https://eprint.iacr.org/2019/1051.pdf
- This is one of the newest cryptographic equations, it's an improvement over the common ECDSA (elliptic curve), which was an improvement over RSA.

It's currently the recommendation for things like DNSSEC. https://essay.utwente.nl/75354/1/DNSSEC%20curves.pdf

>  A newer elliptic curve algorithm, Ed25519, which
uses a so-called Edwards curve has been standardized for use in
DNSSEC in February 2017, citing security problems with the currently
used elliptic curves as a motivation

**Comment by fishseabowl** [comment]
Also, NIST approves RSA, ECDSA, and EdDSA as digital signature standard. please check https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-5-draft.pdf.

**Comment by fishseabowl** [comment]
Resolve this issue on #192
