### ISSUE TITLE
Update docker integration put to use artifact manager

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#195]
Currently the `GET /blobs` reads from the artifact manager but there is no programatic way to write data there.

This is a regression on main 

***

Yes to first question and there will be Erwin's changes as he shown today in demo is to pull from dockerhub if not there locally and then store to local artifact_manager. Second is good question but right now we do not full e2e working mechanism for that but the end thought is to have handle_put_blobs will go through artifact_manager to store the blobs at same place based on digest. Also handle_put_blobs does appending of data, so we have to see how it will play through our current implementation of pu_artifact

_Originally posted by @MitaliBo in https://github.com/pyrsia/pyrsia/pull/161#discussion_r774762169_

**Comment by prince-chrismc** [comment]
https://github.com/pyrsia/pyrsia/pull/175

Did the opposite.

We can now write manifest to the artifact manager but there is no way to extract this data.

***

Our "demo" is broken since we can no longer push and pull 😱

**Comment by prince-chrismc** [comment]
Seems like issue(s) exist?

#195 covers half

**Comment by MitaliBo** [comment]
@prince-chrismc We can close this now as we have mechanism now to pull manifest and blobs from local pyrsia storage and if we don't have it then we pull them from dockerhub and store in pyrsia.
