### ISSUE TITLE
Integrate the bit torrent client with the artifact manager.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#201]
The bittorrent integration has the bittorrent client putting files in a staging directory. This task is to make the file accessible through the artifact manager by its hash. To make this happen, these things will need to happen:
* The bittorrent integration will need to be aware of the desired hash algorithm that will be used to identify the file through the artifact manager. This may not be the same as the hash that was used to identify the file to the bittorent client, so it will need to be one of the inputs to the bittorrent integration.
* The artifact manager will need to have a new method to add a file from the staging directory. The inputs to the new method should be the hash algorithm and the path of the file. The method should use the specified hash algorithm to compute the file's hash and then use the file's hash to move and rename the file so that it can be pulled from the artifact manager by its hash.

This is required by the demo so that it adds the wow factor of being efficient and speed downloads and in the artifact manager we have directory structure based on hash so it is needed to be put in artifact manager so that it is available through "docker pull"

**Comment by fishseabowl** [comment]
I have two questions:
1. where is the staging directory? In the local node or in the distributed file system(including local and remote nodes) 
2. For the artifact manager, what is the purpose of "use the file's hash to move and rename the file"?

**Comment by mgrand** [comment]
@fishseabowl 
> 1. where is the staging directory? In the local node or in the distributed file system(including local and remote nodes)
Elliott's bittorrent integration leaves files in a directory in the node's local file system.
> 2. For the artifact manager, what is the purpose of "use the file's hash to move and rename the file"?
The artifact manager store's files locally, identifying them by a combination of hash algorithm and hash value. It is the mechanism we will use to organize access to docker blobs, manifests and all other types of software artifacts.

**Comment by efrisch** [comment]
Bittorrent and synapse integration is no longer in scope. Closing old tasks that we no longer plan to implement.
