### ISSUE TITLE
Pulling from localhost does not work correctly on mac

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#203]
```
docker pull localhost:7878/some-image
```

works perfectly on Linux. On Mac however, this results in: 

```
~ $ docker pull localhost:7878/some-image
Using default tag: latest
Error response from daemon: Get "http://127.0.0.1:7878/v2/": dial tcp 127.0.0.1:7878: connect: connection refused
```

A temporary work-around exists in using an explicit hostname that resolves to 127.0.0.1 instead of localhost.

**Comment by erwin1** [comment]
The issue looks very similar to https://github.com/docker/for-mac/issues/3611

This can be reproduced even without the Pyrsia node:
$ nc -l localhost 3030

$ docker pull localhost:3030/alpine

I would expect to receive:
```
Using default tag: latest
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

But instead I receive: 
```
Using default tag: latest
Error response from daemon: Get "http://localhost:3030/v2/": dial tcp [::1]:3030: connect: connection refused
```

Even if I open a server socket on port 3030 of the ipv6 local loopback address, I get the same result.

**Comment by erwin1** [comment]
The reason of this issue is that the docker engine, which is running in the Desktop VM, is doing the pulling so a pull for localhost is trying to pull from the VM host, which obviously doesn't run Pyrsia.

There are probably a couple of ways around this issue:
1. try to expose the Pyrsia host port in the Desktop VM somehow
2. use a named host for 127.0.0.1 instead of localhost (which was already described as a work-around)
3. run a Pyrsia node in a docker container and map the port

Ideally the Pyrsia installer would handle any of this, so the user doesn't have to do any manual steps. 
I think 1. will be too 'non-standard' and 3. implies a dependency on docker (which isn't a problem if you want to use Pyrsia for pulling docker images, but we do want to support other artifacts as well), but I think this is worth investigating further. (maybe a Pyrsia docker image could be an alternative way of installing Pyrsia?)

But on the short term, I think option 2. is the most feasible.

**Comment by fishseabowl** [comment]
I prefer option 2, otherwise we might need to integrate Pyrsia with the docker client.

**Comment by erwin1** [comment]
Thanks @fishseabowl 
I agree option 2 is the easiest for now. 

In the long run we might want to provide a dockerized version of the Pyrsia node (next to the installer).
@chris-crone did some experiments on this in: https://github.com/chris-crone/pyrsia/commit/c2b7c7c4a1c3ea5880eb6145c26dc702d9d19a58 and I commenting it here so it doesn't get lost:

Using:
```
docker buildx bake
```

and a docker-compose.yml:
```
services:
  pyrsia:
    image: pyrsia/node
    command: -p 7878
    ports:
      - "7878:7878"
    volumes:
      - pyrsia:/tmp

volumes:
  pyrsia:
```

This brings up the Pyrsia node at port 7878

**Comment by mgrand** [comment]
We will __definitely__ want a dockerized Pyrsia node. The trusted/major nodes that we have discussed will definitely need to run in a cloud environment. The easiest way to do that is to have a docker image for Pyrsia. I would go so far as to say it is a requirement for MVP.

**Comment by erwin1** [comment]
Let me split off the dockerization in a separate issue then, so we can discuss and prioritize.

**Comment by chris-crone** [comment]
I can put up a PR with the work that I did. I'm not a rust expert but my Dockerfile should be a good first stab

**Comment by mgrand** [comment]
@chris-crone The best way to invite people to review your PR is to specify reviewers in the PR. If you specify pyrsia/collaborators for the reviewer, the request will go to all active Pyrsia collaborators.  I have done this for you.

**Comment by erwin1** [comment]
@chris-crone updating Docker Desktop to 4.4.2 (73305) (Engine v20.10.12) caused the 'use a named host for 127.0.0.1 instead of localhost' work-around to fail.

Luckily we do have a dockerized version now 👍 that works around this as well, but we might need to explore other workarounds (like "expose the Pyrsia host port in the Desktop VM somehow") for developers that want to run natively on Mac?

**Comment by erwin1** [comment]
The conclusion for now is that on non-linux platforms, the demo including the docker registry-mirror setting will only work using the dockerized version.

I'm closing this issue.
