### ISSUE TITLE
Demo Script / installation Error

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#210]
Details:
Fetched 7113 kB in 2s (3666 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
gnupg is already the newest version (2.2.19-3ubuntu2.1).
wget is already the newest version (1.20.3-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
Error: Process completed with exit code 2.

**Comment by fishseabowl** [comment]
Possible solution: use "--no-check-certificate" option

**Comment by sbtaylor15** [comment]
Let me check the pgp keys on the website.  They were being overwritten by actions of the forks at one point.

**Comment by sbtaylor15** [comment]
It looks like the website build is wiping out whole gh-pages branch removing the public.key at the same time
