### ISSUE TITLE
Enable the metadata manager to find ProjectVersion structs shared through the Kademlia distributed hash map.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#215]
Given that PackageVersion metadata that describes docker manifests is being shared through Kademlia (see #214), enhance the metadata manager to look for PackageVersion metadata when in Kademlia when it cannot find it in the local document store. 

If the metadata manager finds the PackageVersion in Kademlia, it should store it in the local document store.

**Comment by fishseabowl** [comment]
@mgrand  Could you add the linked PR to related closed issues? This will help with the review. Thanks

**Comment by mgrand** [comment]
@fishseabowl There is no linked PR yet. This is still in the backlog and there will be a few issues to work before this one. See the epic #162 for context.

**Comment by betarelease** [comment]
This is very old and no longer relevant in current structure. Will open a new issue when we really need this. Closing for now.
