### ISSUE TITLE
Make the Document Store More Robust

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#228]
Currently, the document store is built on top of the key-value store UnQLite. It responds to error results from UnQLite without checking to see what the specific error is. This means that there are situations that the document store will not handle well. For example,
* If the error code indicates that the operation could not proceed because another thread's transaction had a lock, the document store will treat the operation as a failure rather than waiting and retrying.
* UnQLite is written in C and manages its memory independently of RUST. If a return code indicates that UnQLite is out of memory, rather than attempting to somehow restart UnQLite the document store will treat it as a normal failure and continue to call UnQLite expecting additional operations to succeed when they won't.
* If UnQLite returns a failure indicating that it cannot open a file due to permission errors, the document store will be unaware of the situation and not report it.

To improve this, one of the following three things should be done:

1. Modify the document store to respond to specific error statuses in an appropriate way. Currently the only way for the document store to tell what the specific UnQLite error is, is to look at the error string associated with the error by the Rust wrapper. A complete list of these is in UnQLite's error.rs:
```
    pub fn error(&self) -> &str {
        match self.kind {
            ErrorKind::NOMEM => "Out of memory",
            ErrorKind::ABORT => "Another thread have released this instance",
            ErrorKind::IOERR => "IO error",
            ErrorKind::CORRUPT => "Corrupt pointer",
            ErrorKind::LOCKED => "Forbidden Operation",
            ErrorKind::BUSY => "The database file is locked",
            ErrorKind::DONE => "Operation done",
            ErrorKind::PERM => "Permission error",
            ErrorKind::NOTIMPLEMENTED => "Method not implemented by the underlying Key/Value storage engine",
            ErrorKind::NOTFOUND => "No such record",
            ErrorKind::NOOP => "No such method",
            ErrorKind::INVALID => "Invalid parameter",
            ErrorKind::EOF => "End Of Input",
            ErrorKind::UNKNOWN => "Unknown configuration option",
            ErrorKind::LIMIT => "Database limit reached",
            ErrorKind::EXISTS => "Record exists",
            ErrorKind::EMPTY => "Empty record",
            ErrorKind::COMPILE_ERR => "Compilation error",
            ErrorKind::VM_ERR => " Virtual machine error",
            ErrorKind::FULL => "Full database (unlikely)",
            ErrorKind::CANTOPEN => "Unable to open the database file",
            ErrorKind::READ_ONLY => "Read only Key/Value storage engine",
            ErrorKind::LOCKERR => "Locking protocol error",
            ErrorKind::OK => unreachable!(),
            ErrorKind::__Nonexhaustive => unreachable!(),
        }
    }
```
A drawback of this approach is that if any of the wrapper's error messages ever change, they will not be recognized by the document store.

2. Modify the document store to respond to the numeric error status produced by UnQLite. <br>
The error that is returned by the UnQLite wrapper is a `struct` named `Custom`. It contains the numeric error status returned by UnQLite and the `ErrorKind` enum variant that the wrapper associates with the numeric error status. Unfortunately, the wrapper has these fields declared private and no methods are provided to access the fields.<br>
I have created an [issue for UnQLite to fix this](https://github.com/zitsen/unqlite.rs/issues/14). Since the most recent commit to UnQLite at the time of this writing is 15 months ago, we many find that the maintainers of UnQLite will not respond to this issue in a timely manner. If this is the case, we may consider making the fix in our own fork of the UnQLite wrapper.

3. Replace UnQLite with [Sled](https://github.com/spacejam/sled). Sled is actively maintained and is 100% Rust.  I suggest this because we may eventually have to replace UnQLite anyhow. The reason for that is that UnQLite is thread safe only on Windows and Unix-like operating systems. To make it thread safe on other operating systems, we would have to add another operating-system-specific mutex mechanism to UnQLite.<br>
Since Sled is all Rust, it goes anywhere Rust goes. The reason that I suggest switching before MVP is that it allows us to avoid the headache of having to write a utility to convert UnQLite files to Sled.

**Comment by tiainen** [comment]
UnQLite is no longer being used for the underlying database.
