### ISSUE TITLE
Fix Code Coverage Reports

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#230]
When I look at https://app.codecov.io/gh/pyrsia/pyrsia I see
>Coverage is either being processed, there has been no coverage report uploaded, or there was an error processing.

There is a problem with the code coverage reports. This task is to make them work again.

**Comment by prince-chrismc** [comment]
> This task is to make them work again.

They never worked FYI

**Comment by sbtaylor15** [comment]
@prince-chrismc i have the dockerfile sorted out so it will build locally.  Let me get it cleaned up and PR created.

**Comment by sbtaylor15** [comment]
Fixed in #260
