### ISSUE TITLE
Post-install configuration for Docker

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#233]
After the apt-get install, the installer should guide the user how to configure Docker so it will use Pyrsia.

In the easiest form, this could simply be printing out:
```
To configure Docker to use Pyria, open your Docker daemon config file (usually at /etc/docker/daemon.json) and add this in the root object:
  "registry-mirrors": ["http://localhost:7888"],

For more information see [link to the end-user docs on pyrsia.io]
```

**Comment by prince-chrismc** [comment]
Hmm 🤔 I'd expect the installer to handle this... or print a warning if it can not (docker was not installed for example)

**Comment by sbtaylor15** [comment]
PR merged closing.
