### ISSUE TITLE
Create integration tests

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#234]
(nice to have but not need for demo)

To start with, this could be a first integration test:

- start up 2 Pyrsia nodes
- docker pull an image from one node
- docker pull the same image from the other node
- check that the second node got its data from the first node

*start with the simple script - shell script or something that could run the readme*

**Comment by karolh2000** [comment]
@erwin1 @tiainen Hi, I was thinking to create a integration tests for the current functionality (maven, docker, nodes connectivity, etc), is there any work being done except #664? Before I start working on it I want to make sure I'm not clashing with anybody else and nobody else if already working on it. Thanks!

**Comment by tiainen** [comment]
There is no other work done, so feel free to work on this.

**Comment by tiainen** [comment]
Fixed with https://github.com/pyrsia/pyrsia-integration-tests/pull/1
