### ISSUE TITLE
Allow Artifact Manager to Move files from Directories

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#238]
Add a method to the artifact manager named `move_from` to move a file from a directory into the artifact manager.  Also change the artifact manager to use base58 encoding for its file names.

**Comment by betarelease** [comment]
Looks like this needs to be two separate issues. Changing to base58 should be handled on its own.

**Comment by betarelease** [comment]
Also can you add reasons why we need the move_from now(before the demo)?

**Comment by mgrand** [comment]
@betarelease The bit torrent client will leave files in a directory. Once a file is fully downloaded, it needs to be moved into the artifact manager to be accessible by its hash.

**Comment by mgrand** [comment]
@betarelease The change to base58 is a very small change that I have already coded. It does not need worth a separate PR cycle, which typically takes a day or two. The change consists of 
* add the bs58 create to cargo.toml
* add an extern crate declaration in artifact_manager.rs
* replaced four instance of hex::encode with bs58::encode

If you think that is a problem I will make it a separate issue.
