### ISSUE TITLE
Pyrsia CLI to have a default config

### ISSUE THREAD

**Issue by MitaliBo** [pyrsia/pyrsia#242]
Right now once the cli is installed , user has to add config using "pyrsia config --add" to write to conf file , we can add a default config with default port, which needs initialization of config file at the time of installation

**Comment by betarelease** [comment]
Use $HOME/.config to place these files

**Comment by MitaliBo** [comment]
@sbtaylor15 do we have cli config file also added in the installer? if not then we need to add "pyrsia-cli.conf" file which will have: 
{
    "host" : "127.0.0.1",
    "port" : "7888",
    "artifacts_storage_allocated_size" : "10.84 GB" ( have to discuss this value)
}

The env var for the file location we can keep "PYRSIA_CLI_CONF_FILE" and i will use this var to update the code
