### ISSUE TITLE
Explore: How to deal with logs in release build

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#244]
The release build doesn't show any output by default, while one of the things we will show in the demo is log output to show where an artifact came from.

This ticket is to find out how to deal with this.

**Comment by erwin1** [comment]
So there're a couple of things to note:

- we use the env_logger in pyrsia_node currently
- so the release builds do contain logs, they just need to be configured. e.g. with RUST_LOG env variable
- the release build doesn't exclude any log levels by default, but I think we should limit release builds to INFO logs

I'll create a PR to:
- limit logs in release builds to INFO
- set RUST_LOG in the dockerized version

@sbtaylor15 I'll create a separate issue for the Linux installer.

**Comment by sbtaylor15** [comment]
Added RUST_LOG=info in pyrsia-node docker image. PR #260
