### ISSUE TITLE
Configure logging in the Pyrsia linux installer

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#251]
Discovered in #244 

We should configure logging in the apt-get installed version of Pyrsia, so that a user can somehow inspect the logs if necessary.

The release binary contains log (INFO and higher) but they are only printed if the `RUST_LOG` env variable is set to `info`

- the script starting the Pyrsia node should set `RUST_LOG=info` 
- it could then redirect that output to a file?

**Comment by sbtaylor15** [comment]
Using stdout and stderr will give us the most flexibility.  When running in docker stdout and stderr can be view using the `docker logs`.  Same when the container is running in Kubernetes, `kubectl logs`.  Running natively in Ubuntu under systemctl the output will be sent to syslog and viewed with `systemctl status` or `journalctl -u pyrsia.service`

**Comment by erwin1** [comment]
Great, then I think simply setting `RUST_LOG=info` is all we need to do. It will then print info logs and higher to stderr.

**Comment by sbtaylor15** [comment]
Ok, I will make sure that is set for the service

**Comment by sbtaylor15** [comment]
Added RUST_LOG=info to pyrsia-node docker image in PR #260
