### ISSUE TITLE
Fix dockerized version of Pyrsia node

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#253]
2 little things are missing to make the dockerized version work:
- make the Pyrsia server host configurable so it can bind on 0.0.0.0 instead of 127.0.0.1
- install the latest ca-certificates in the container

**Comment by erwin1** [comment]
@sbtaylor15 thanks. openssl isn't installed by the Dockerfile, but `libssl1.1` is. 

And `apt-get install ca-certificates` fixes the issue. Unless you think `openssl` should be installed instead?

**Comment by sbtaylor15** [comment]
@erwin1 openssl is now a required dependency.  When we do `apt-get install pyrsia` openssl gets installed if missing.  Realistically, the dockerized version shouldn't do a cargo build but install pyrsia using apt-get.  That way we are testing what the end user (native Ubuntu) is doing.

**Comment by sbtaylor15** [comment]
Added docker build in PR #260 to create image and push to dockerhub based on apt-get installer.
