### ISSUE TITLE
participate in google summer of code (gsoc)

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#258]
Need to apply by Feb 21.

When proposals are submitted they will be selected as a medium (175 hour) or large (350 hour) project. The standard coding period will be 12 weeks. 

https://developers.google.com/open-source/gsoc/timeline

**Comment by prince-chrismc** [comment]
Seems like we missed the deadline so this can be closed 😭 


https://developers.google.com/open-source/gsoc/timeline

>February 21 - 18:00 UTC
Mentoring organization application deadline
