### ISSUE TITLE
pyrsia node default port change from 7878

### ISSUE THREAD

**Issue by MitaliBo** [pyrsia/pyrsia#259]
As pointed by Mark 7878 is already assigned in the IANA registry. See https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=7878

We should choose a different port number and register it with IANA. Some currently unassigned port number ranges are 7873-7877, 7881-7886 and 7888-7899

**Comment by sbtaylor15** [comment]
Updated pyrsia-node docker image to expose 7888.  PR#260

**Comment by mgrand** [comment]
@erwin1 You linked a PR that will close this issue. This issue should not be closed until we have registered Pyrsia's use of port 7888 with IANA.  Have you done that?

**Comment by MitaliBo** [comment]
created #285 for IANA registration so closing this one
