### ISSUE TITLE
Manually stand up a Synapse node on Google Cloud.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#265]
Stand up a publicly accessible Synapse node on GCP using using the Google Compute Engine. 

This task will be complete when it is possible synapse nodes on developer machines to interact with the public Synapse node.

we do have `pyrsia.link` as a domain name to use this.

**Comment by mgrand** [comment]
There does not appear to be a docker image for this in dockerHub, So I am building one. 

A prerequisite is cross-compiling for linux.

**Comment by mgrand** [comment]
The previous problem was solved with
```
export TARGET_CC=x86_64-linux-musl-gcc
```
However this just got me to problem with compiling OS-specific C code used by Synapse. Will try to switch to a container based build.

**Comment by mgrand** [comment]
@sbtaylor15 I have added Steve Taylor to this ticket as he is doing most of the work. He is finishing the docker file and standing it up in a k8s cluster on GCP. I expect that I will be doing some manual testing after Steve is done.

**Comment by sbtaylor15** [comment]
Using GCP instead of GKE since synapse has not really been deployed into a Kubernetes environment.  Needs a bit more work for k8s.  

See #267 for details.
