### ISSUE TITLE
Create devops automation to stand up the Synapse node on GCP.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#267]
This task is to automate the creation and re-creation of the Synapse node stood up for issue #265 using the details documented for issue #266

**Comment by sbtaylor15** [comment]
The machine is up and running on GCP.   Running the pyrsia/synapse fork.  Synapse will startup automatically on reboot.  50gig download drive is being used.  IP addr is 104.198.67.189 and can be accessed using synapse.webredirect.org.

**Comment by sbtaylor15** [comment]
May want to use Terraform down the road to provide a way to stand up on any cloud provider for a production setting.
