### ISSUE TITLE
Fix Synapse -> rpc cargo audit issues which are blocking Merge

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#271]
```
Calling cargo-audit (JSON output)
  /home/runner/.cargo/bin/cargo audit --json
  {"database":{"advisory-count":393,"last-commit":"9839c6ee0fdc486eea186f36ee8efd1f32d368f2","last-updated":"2022-01-24T14:39:43Z"},"lockfile":{"dependency-count":443},"settings":{"target_arch":null,"target_os":null,"severity":null,"ignore":["RUSTSEC-2020-0159"],"informational_warnings":["unmaintained"],"package_scope":null},"vulnerabilities":{"found":true,"count":1,"list":[{"advisory":{"id":"RUSTSEC-2022-0006","package":"thread_local","title":"Data race in `Iter` and `IterMut`","description":"In the affected version of this crate, `{Iter, IterMut}::next` used a weaker memory ordering when loading values than what was required, exposing a potential data race\nwhen iterating over a `ThreadLocal`'s values.\n\nCrates using `Iter::next`, or `IterMut::next` are affected by this issue.","date":"2022-01-23","aliases":[],"related":[],"collection":"crates","categories":["memory-corruption"],"keywords":[],"cvss":null,"informational":null,"url":"https://github.com/Amanieu/thread_local-rs/issues/33","references":[],"withdrawn":null},"versions":{"patched":[">=1.1.4"],"unaffected":[]},"affected":null,"package":{"name":"thread_local","version":"0.3.6","source":"registry+https://github.com/rust-lang/crates.io-index","checksum":"c6b53e329000edc2b34dbe8545fd20e55a333362d0a321909685a19bd28c3f1b","dependencies":[{"name":"lazy_static","version":"1.4.0","source":"registry+https://github.com/rust-lang/crates.io-index"}],"replace":null}}]},"warnings":{}}
Warning: 1 vulnerabilities found!
```

**Comment by erwin1** [comment]
```
├── synapse-rpc v0.1.20
...
│   ├── regex v0.2.11
...
│   │   ├── thread_local v0.3.6
```

and we need we need thread_local >=1.1.4

**Comment by efrisch** [comment]
Forked to https://github.com/efrisch/synapse-rpc
Have cleaned up everything except chrono.
It seems like the recommended replacement is https://github.com/time-rs/time
Necessary function is `Utc::now()`

NOTE: Update `Cargo.toml` to use `synapse-rpc` as
`synapse-rpc = { git = "https://github.com/efrisch/synapse-rpc" }`

**Comment by tiainen** [comment]
@efrisch I've worked a bit more on this and managed to replace the `chrono` crate with the `time` crate. I also upgraded the `url` crate from 1 to 2.2.2 as you had already found out. Updating `Cargo.toml` to use the following synapse-rpc declaration fixes all audit issues:

    synapse-rpc = { git = "https://github.com/tiainen/synapse", branch = "pyrsia-synapse" }

I have currently implemented it by forking the entire official [Luminarys/synapse](https://github.com/Luminarys/synapse) repository instead of only synapse-rpc folder. We should probably fork this directly under the pyrsia organisation.

**Comment by efrisch** [comment]
I've updated my Cargo.toml to use that synapse-rpc line; I get
    Updating crates.io index
error: failed to select a version for `time`.
    ... required by package `synapse-rpc v0.1.21 (
https://github.com/tiainen/synapse?branch=pyrsia-synapse#b1420d11)`
    ... which satisfies git dependency `synapse-rpc` of package `pyrsia
v0.1.0 (/Users/elliottf/src/pyrsia)`
    ... which satisfies path dependency `pyrsia` (locked to 0.1.0) of
package `pyrsia_cli v0.1.0 (/Users/elliottf/src/pyrsia/pyrsia_cli)`
versions that meet the requirements `^0.3.6` are: 0.3.6

Elliott

Elliott Frisch *|* Block Chain Developer *|* JFrog
Mobile: *+1.770.256.6094*

**Comment by mgrand** [comment]
@tiainen @betarelease I previously had a work-around in the code that used the time crate to replace the use of chrono in formatting and parsing timestamps for signatures. The work around also used the iso8601 crate to format and parse dates. To make it work I had to write format and parse functions that supplied formatting strings. 

Sudhindra noticed the code and told me to rip it out. He said it was unacceptable to for us to have any time manipulation code in our code base. He said it would be better to have and exception configured for cargo audit than to have the work-around. That is the reason that we have cargo audit configured to ignore RUSTSEC-2020-0159 with the file in `.github/workflows/.cargo/audit.toml`.

If your work-around involves adding ANY time-related code to our code-base, you may want to check with Sudhindra to see if he would prefer a configuration to ignore the vulnerability to your adding the code.

**Comment by efrisch** [comment]
I updated signed_struct to use the time version cargo suggested, and I can
build! We will still fail the audit process though, because
```
 cargo audit
    Fetching advisory database from `
https://github.com/RustSec/advisory-db.git`
      Loaded 394 security advisories (from
/Users/elliottf/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (435 crate dependencies)
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!
Dependency tree:
chrono 0.4.19
├── signed 0.1.0
│   ├── signed_struct 0.1.0
│   │   ├── pyrsia_node 0.1.0
│   │   └── pyrsia 0.1.0
│   │       ├── signed_struct 0.1.0
│   │       ├── signed 0.1.0
│   │       ├── pyrsia_node 0.1.0
│   │       └── pyrsia_cli 0.1.0
│   └── pyrsia 0.1.0
└── pyrsia_node 0.1.0

error: 1 vulnerability found!
```
So I think we need to ignore chrono again.

Elliott Frisch *|* Block Chain Developer *|* JFrog
Mobile: *+1.770.256.6094*
