### ISSUE TITLE
Modify the artifact manager to make every torrent available through the DHT.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#281]
This is to be done after #280. 

This task is to modify the artifact manager to publish its .torrent files in the distributed hash table (DHT). The contents of the torrent will be inserted into the DHT as a value with a key that is a [multihash](https://multiformats.io/multihash/). The multihash will contain the hash algorithm and hash value that the artifact manager uses to identify the artifact.

Before inserting an entry in the DHT, the artifact manager should check to see if there is already an entry with the given multihash. If there is then instead of inserting an entry, it should check that the torrent in the DHT is the same as the torrent created locally. If it is not the same, then this is a discrepancy that should be logged as an error.

Insertion of torrent files into the DHT should happen when a new artifact is pushed to the artifact manager. 

On start-up, we should check that all of the locally available torrents are in the DHT. We should repeat this every 24 hours. This is to be sure that nothing disappear from the DHT. We should log the results of this so that we can fine tune how often this should happen and which nodes need to do this.

There should be a test that runs a separate process just to verify that expected artifacts are available in the DHT.

Keep the size of the PRs down, I am splitting this into two sub-issues:

- [x] #305
- [x] #306

**Comment by mgrand** [comment]
This is an explanation of the reason we are using RwLock and Mutex in artifact_manager: (This comment is not yet finished)

**Comment by betarelease** [comment]
The 24 hour repetition should be separated from this ticket

`On start-up, we should check that all of the locally available torrents are in the DHT. We should repeat this every 24 hours. This is to be sure that nothing disappear from the DHT. We should log the results of this so that we can fine tune how often this should happen and which nodes need to do this.`

**Comment by efrisch** [comment]
Bittorrent and synapse integration is no longer in scope. Closing old tasks that we no longer plan to implement.
