### ISSUE TITLE
CLI won't build on MacOS 12.1 with vanilla Rust installation (xcrun is missing)

### ISSUE THREAD

**Issue by jbaruch** [pyrsia/pyrsia#288]
I've tried to build using the readme and got the following error while building the CLI:

note: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

From what I remember it's the xcode command line tools or something is missing? Should probably be added to the readme instructions.

**Comment by jbaruch** [comment]
I've tried to build using the readme and got the following error while building the CLI:

`note: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

From what I remember it's the `xcode` command line tools or something is missing? Should probably be added to the readme instructions.

**Comment by MitaliBo** [comment]
@jbaruch yes it is asking developer tool to be installed. Can you please do "$ xcode-select --install" and let me know if that works? since most of the developers usually have xcode installed or have rust plugin in IDE, so that is why we might have not seen this.

**Comment by betarelease** [comment]
Closing this since it looks like xcode is required for running developer tools for rust
