### ISSUE TITLE
Configure pyrsia artifacts storage directory with correct permissions

### ISSUE THREAD

**Issue by MitaliBo** [pyrsia/pyrsia#302]
During installation we want to have a directory named "pyrsia" setup with all the permissions which can be used for Artifacts storage and retrieval. As of current code we create "pyrsia" in current directory. This directory path should be set as env variable which can be used in code

**Comment by sbtaylor15** [comment]
@MitaliBo I am assuming 644 for the permission will work.  Correct?

**Comment by MitaliBo** [comment]
yes i think that would do

**Comment by MitaliBo** [comment]
We have "PYRSIA_ARTIFACT_PATH=/usr/local/var/pyrsia" set and env var is exposed which now can be consumed in code.
