### ISSUE TITLE
artifactory_manager::space_used does not count the space taken by directories

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#304]
`artifactory_manager::space_used` does not count the space taken by directories.  This does not amount to much of a difference now, because there are only two directories.

After the the artifact manager is modified to allow it to scale to hundreds of millions of artifacts, there will be many directories and this discrepancy will be significant.

**Comment by prince-chrismc** [comment]
No longer seems relevant
//cc @MitaliBo
