### ISSUE TITLE
Test cases for blobs module

### ISSUE THREAD

**Issue by MitaliBo** [pyrsia/pyrsia#307]
Right now we do not have any test coverage for /docker/v2/blobs module, this issue is to cover that

Move "        hex::decode(&digest.get(7..).unwrap()).unwrap().as_ref(),
" in new function

**Comment by betarelease** [comment]
As part of the testing, 

these hardcoded urls should become injectable

"/tmp/registry/docker/registry/v2/repositories/{}/_manifests/tags/{}/current/link",

"/tmp/registry/docker/registry/v2/blobs/sha256/{}/{}/data",

"http://localhost:7878/v2/{}/manifests/sha256:{}",

"/tmp/registry/docker/registry/v2/repositories/{}/_uploads/{}/data",

"/tmp/registry/docker/registry/v2/repositories/{}/_uploads/{}",

These urls need to be derived from a configuration setting and the processing needs to be relative to that. The test should allow me to specify a different starting directory but still the code should work.
