### ISSUE TITLE
Research what `rust-strip` does; and whether we should include it in our release build process.

### ISSUE THREAD

**Issue by efrisch** [pyrsia/pyrsia#314]
Part of `cargo-binutils`, performing a release build produces a 14 MB executable. Running `rust-strip` on that reduces the size to 10 MB. How?

**Comment by sbtaylor15** [comment]
We can add the strip when we create the .deb.

**Comment by mgrand** [comment]
@efrisch What it is doing is stripping out the debug information.

**Comment by sbtaylor15** [comment]
@mgrand do we need to run the strip against a release build. I am assuming the release binaries don't contain any debug symbols.  Can you please confirm?

**Comment by mgrand** [comment]
I don't see any reason for release binaries to contain debug info. That assumes we are well enough organized to reproduce the release with debug info in the unlikely event it is needed.

**Comment by sbtaylor15** [comment]
Ok, I will verify that the installed binaries from the apt-get don't contain any debug symbols.

**Comment by efrisch** [comment]
@mgrand That is the point of the ticket. I'll reiterate that stripping a
*release* build drops the executable size from 14MB to 10MB.
$ cargo build --release
$ ls -l ../target/release/pyrsia_node
-rwxr-xr-x 2 elliottf staff 14716880 Feb  2 11:09
../target/release/pyrsia_node
$ rust-strip ../target/release/pyrsia_node
$ ls -l ../target/release/pyrsia_node
-rwxr-xr-x 1 elliottf staff 10762248 Feb  3 09:11
../target/release/pyrsia_node

Compared to ~70MB and 28MB for non-release.
$ cargo build
$ ls -l ../target/debug/pyrsia_node
-rwxr-xr-x 2 elliottf staff 67685568 Feb  2 11:21
../target/debug/pyrsia_node
$ rust-strip  ../target/debug/pyrsia_node
$ ls -l ../target/debug/pyrsia_node
-rwxr-xr-x 1 elliottf staff 28396980 Feb  3 09:13
../target/debug/pyrsia_node



Elliott Frisch *|* Block Chain Developer *|* JFrog
Mobile: *+1.770.256.6094*

**Comment by sbtaylor15** [comment]
@efrisch interesting.  I would have thought that the release build stripped everything and made them as small as possible.  I will make sure the binaries are stripped as part of creating the .deb.

**Comment by efrisch** [comment]
Steve That's why I started making noise yesterday; I too was surprised!

**Comment by sbtaylor15** [comment]
rust-strip runs the OS level `strip` which is equivalent to running `ld -s` at link time.  Basically, strip everything.
