### ISSUE TITLE
Explore/Spike: Call a vector of mutable objects multiple times

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#315]
We'd like to explore an observer, event subscription, model for the Blockchain "output" API

### Idealistic (Chris + Christian)

```rust
let mut magic_number = 5
let expensive_closure = |num| {
      println!("calculating slowly...");
      thread::sleep(Duration::from_secs(2));
      magic_number = magic_number + num
};

expensive_closure(5);
expensive_closure(10);

println!("Magic number is: {}", magic_number); // Expect 20 to be printed
```

###

**Comment by fishseabowl** [comment]
fn main() {

    let mut magic_num = 5;
    
    let **mut** ex = |num| {
        println!("Slow");
        magic_num+=num;
        num
    };
    
    ex(5);
    ex(10);
    
    println!("magic_num {}", magic_num);
}

Output:
Slow
Slow
magic_num 20

**Comment by chb0github** [comment]
This is ideally what I would like:

```rust

fn add_transaction(& transaction: Transaction, callBack: Fn) -> Result<Block,Err> {
 // lowest level
}
fn add_blockchain_listener(bc: &Blockchain, callBack: Fn) -> Result<Block,Err> {
 // highest level
}

fn add_block_listener(block: Block, callBack: Fn) -> Result<Block,Err> {
   // middle level
}

add_transaction(&t, |block_chain| saveToFile(block_chain))
add_transaction(&t)
blockchain.add_finalizer_listener(|finalBlock| saveToFile(finalBlock))
```

**Comment by prince-chrismc** [comment]
This answered our technical question 🎉

**Comment by mgrand** [comment]
Do you have a use case for blockchain events?  If you do, it becomes clearer what a good solution looks like. If you don't, maybe it is not needed.
