### ISSUE TITLE
rename pyrsia/synapse master branch to main for inclusive naming

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#325]

**Comment by betarelease** [comment]
This was changed using github ui. So marking it complete

**Comment by betarelease** [comment]
Need to ensure that the corresponding github action is fixed and it should point to main instead of master

**Comment by sbtaylor15** [comment]
@betarelease @prince-chrismc - We are using the rust workflow from pyrsia/prysia to build synapse and package into a .deb.  Doing that to keep Synapse and Pyrsia in sync and to avoid the need for additional tokens/security in place.

See PR pyrsia/pyrsia#328

I will fix the old references so we don't forget about them.
