### ISSUE TITLE
Spike/Explore: Treat genesis block as normal block with hardcoded values

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#329]
I don't think you should be treating the genesis block as exceptional. It's a normal block with hardcoded values

_Originally posted by @chb0github in https://github.com/pyrsia/pyrsia/pull/323#discussion_r799676575_

**Comment by fishseabowl** [comment]
Thanks for the comments. The genesis block is a special block. And it is only created once when the blockchain is first built. So we can store this block into a file. And when other nodes join the network, they may use a new method "sync init"(under development) to initialize and synchronize the blockchain.

**Comment by prince-chrismc** [comment]
This is an explore/spike... there has been no decisions made. It's an open topic thats evolving.

Thank you for disagreeing and sharing your thoughts but we have not weighed this against all the other moving parts we need to incorporate.

**Comment by fishseabowl** [comment]
This is the part of #357. I am closing this issue.

**Comment by chb0github** [comment]
I'm not sure this is a "explore" - I'm actively working on it
