### ISSUE TITLE
Commit node needs to verify transactions are only included once in the same block

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#331]
Perhaps this can be solves with changes from VEc to BTree? :thinking:

***

Is there something like a `SortedSet` in rust? If we use a sorted set then these transactions will naturally stay sorted.

_Originally posted by @chb0github in https://github.com/pyrsia/pyrsia/pull/323#discussion_r799677791_

**Comment by betarelease** [comment]
Navigating to #323 did not reveal what this comment is related to (atleast not after spending time to expand all comments). can you elaborate here what this actually helps with?

**Comment by betarelease** [comment]
closing this since there has been no additional info for a while now.
