### ISSUE TITLE
Refactor signature structure to use `ed25519_dalek` crate 

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#333]
It would be nice if we can use the edwards key library like I had done https://github.com/prince-chrismc/pyrsia-sandbox/blob/a9333aced792e1017db1f424eb1b4b77c7803aa4/src/block_chain/crypto.rs#L28

This way there will be less conflicts for #322

_Originally posted by @prince-chrismc in https://github.com/pyrsia/pyrsia/pull/323#discussion_r799692421_

**Comment by sbtaylor15** [comment]
Does `ed25519_dalek` still depend upon openssl at the OS level?

**Comment by betarelease** [comment]
Based on the description I did not understand where this particular trick can/should be used?

Can you clarify what is happening currently and how this change would be better?

**Comment by prince-chrismc** [comment]
> Based on the description I did not understand where this particular trick can/should be used?
> 
> Can you clarify what is happening currently and how this change would be better?

I have unresolved all the related comments in the PR so the links 

As mention in #332 this is just a temporary step so that we can import everything into the main repo.

As mentioned in out zoom, the consensus library has strict requirements for signing and this is what we currently have. It will mean less conflicts for #322

**Comment by prince-chrismc** [comment]
> Does `ed25519_dalek` still depend upon openssl at the OS level?

Hard to say, https://github.com/dalek-cryptography/ed25519-dalek/blob/ad461f4f0f56507a2945510dedb914b3d3547c40/Cargo.toml#L24 I'd say no but crate dependencys are a rat nest 🤢

**Comment by mgrand** [comment]
If you are concerned about the dependency on OpenSSL there is an issue for replacing it with an all Rust substitute named rusTLS. See #181

**Comment by fishseabowl** [comment]
I don't think it depends on Openssl. It is pure-Rust elliptic curve cryptography. And the dependency tree looks like: 
│   │   ├── ed25519-dalek v1.0.1
│   │   │   ├── curve25519-dalek v3.2.0
│   │   │   │   ├── byteorder v1.4.3
│   │   │   │   ├── digest v0.9.0
│   │   │   │   │   └── generic-array v0.14.5
│   │   │   │   │       ├── serde v1.0.133 (*)
│   │   │   │   │       └── typenum v1.15.0
│   │   │   │   │       [build-dependencies]
│   │   │   │   │       └── version_check v0.9.4
│   │   │   │   ├── rand_core v0.5.1
│   │   │   │   │   └── getrandom v0.1.16
│   │   │   │   │       ├── cfg-if v1.0.0
│   │   │   │   │       └── libc v0.2.112
│   │   │   │   ├── subtle v2.4.1
│   │   │   │   └── zeroize v1.3.0
│   │   │   │       └── zeroize_derive v1.2.2 (proc-macro)
│   │   │   │           ├── proc-macro2 v1.0.36 (*)
│   │   │   │           ├── quote v1.0.14 (*)
│   │   │   │           ├── syn v1.0.85 (*)
│   │   │   │           └── synstructure v0.12.6
│   │   │   │               ├── proc-macro2 v1.0.36 (*)
│   │   │   │               ├── quote v1.0.14 (*)
│   │   │   │               ├── syn v1.0.85 (*)
│   │   │   │               └── unicode-xid v0.2.2

**Comment by prince-chrismc** [comment]
Thanks @fishseabowl for confirming!
