### ISSUE TITLE
Currently the synapse-rpc password is hardcoded

### ISSUE THREAD

**Issue by efrisch** [pyrsia/pyrsia#339]
Currently we have a hardcoded default password for synapse rpc integration. We should make that a default and read the synapse configuration file(s)
   "./config.toml",
    "$XDG_CONFIG_HOME/synapse.toml",
    "~/.config/synapse.toml"
(if present - as synapse does) they will contains an `[rpc]` header with a `password` field.

Also, we should enable overriding that rpc password value from the command line.

**Comment by sbtaylor15** [comment]
@efrisch Synapse .deb installs the default example config file provided by Synapse itself.  The Pyrsia .deb installs the Pyrsia version of the Synapse config (under its installation location) and then restarts Synapse using that config file.  The postinst script for Pyrsia updates the password in the config based on a hard-coded value from that postinst script.

The password should come from a file external to the config.  A command-line override will show up in the `ps -ef` output.  Also, an environment variable will be visible as plain text in the pyrsia.service definition file.

**Comment by sbtaylor15** [comment]
@efrisch I was thinking of something along the lines of how ssl cert files live outside of an nginx config file.  They are put in a place that only the userid running the process has access to.

**Comment by efrisch** [comment]
Closing due to bittorrent stories being out of scope / replaced with bitswap.
