### ISSUE TITLE
Demo Script:Installation job in Github Actions failed

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#341]
Github Actions:: Demo.yml  :: Installation job failed when I push the code.

Details is as the below:
Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:4 https://pyrsia.io/repo bionic InRelease

_**Err:5 https://pyrsia.io/repo bionic Release
  404  Not Found [IP: 185.199.111.1[53](https://github.com/fishseabowl/pyrsia/runs/5128239510?check_suite_focus=true#step:2:53) 443]**_

Hit:6 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:8 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
Reading package lists...

_**E: The repository 'https://pyrsia.io/repo bionic Release' does not have a Release file.
Error: Process completed with exit code 100.**_

**Comment by sbtaylor15** [comment]
@fishseabowl can you please add a link to the log?  I believe this should be fixed.

**Comment by sbtaylor15** [comment]
@fishseabowl looks like the following run worked correctly.  I think it was just a problem with GitHub itself.  Please try running the workflow again.

**Comment by prince-chrismc** [comment]
I think it's an actual problem, it seems his branch points to the older distro that we are no longer build... seem the apt publish is not saving the old information

![image](https://user-images.githubusercontent.com/16867443/153262341-ddaff0c4-4891-4bc0-b282-00ba832d7be5.png)

**Comment by sbtaylor15** [comment]
@prince-chrismc @fishseabowl  Yes, bionic has been removed and replaced with focal.  Fetching and merging the upstream with your local should get everything pointing to focal.  FYI, our apt repo only allows for one version of the OS.   That is why we had to delete bionic.

**Comment by fishseabowl** [comment]
Thanks for the help. Everything works fine now.
