### ISSUE TITLE
Pyrsia node: don't read from stdin

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#349]
The pyrsia_node still reads from stdin for what it looks like demo or debugging purposes. 

It might not a problem, but the node probably shouldn't do this. All interactions with the node should happen using exposed APIs (at the moment either using the docker client or the CLI client)

**Comment by mgrand** [comment]
@prince-chrismc I talked to Mitali today. She confirmed that she is not using the "peers" command, so we can get rid of that. If @efrisch  confirms that we are not using "magnet", then it can all go.

**Comment by MitaliBo** [comment]
If @efrisch needed the magnet one then we can move move that too also to message event as we have for peers

**Comment by erwin1** [comment]
I can confirm the problems with running in the background are related to this reading from stdin

I'll await @efrisch's response on the magnet topic: either remove it or convert it to a message

**Comment by efrisch** [comment]
@MitaliBo I think we should convert it to a message event.
