### ISSUE TITLE
A Pyrsia node can be started anywhere and join the p2p network

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#364]
Unless nodes are connected to each other directly, we should not assume a broadcast or multicast based discovery will allow any node to join the Pyrsia network. The node itself needs to have build-in information that should be sufficient to do the bootstrap process.
We currently launch a node with a `-P` option which contains the name of an existing node in the network. This is great for testing. For production, however, we must make sure that the node knows at least one other node in the network. This can be done by having an IP address or a list of addresses in the node itself (or distributed with it, in a config file).
This has similarities with the DNS resolution issue, where the lookup tools themselves know the addresses of root nameservers and how to contact them.

In a next phase, additional tools like Anycast or GeoDNS can be used to enhance the bootstrapping.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/9695589/157306481-2d042eb0-972a-49ab-be73-5aaba5f4279c.png">

UDPATED: re-worked the above image to clarify the concepts

**Comment by betarelease** [comment]
Let's review if this is completely done. If not lets list what is remaining out of this.

**Comment by betarelease** [comment]
@erwin1 @fishseabowl @tiainen ^^ Is this done in the current state. I see that we can join the p2p network with default setup.

**Comment by erwin1** [comment]
this is done. we could see #1446 as a remaining issue, but let's close this one.
