### ISSUE TITLE
Inclusive linting workflow is not being ran on new PRs

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#387]
This is is never being ran 😕 

![image](https://user-images.githubusercontent.com/16867443/155403406-05ad545e-7369-4020-8016-00a28db47a89.png)

_Originally posted by @prince-chrismc in https://github.com/pyrsia/pyrsia/issues/187#issuecomment-1049188529_

**Comment by sbtaylor15** [comment]
@prince-chrismc per your direction we moved the inclusive naming into the Lint Workflow.  The woke workflow is no longer used.  GitHub does not have a way to delete old workflows at this time.
