### ISSUE TITLE
Create a document store layer above key value store for looking up metadata.

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#39]
# Background
Our architecture calls for a document store to hold metadata and blockchain pages. We are planning to use an library named [UnQLite](https://docs.rs/unqlite/1.5.0/unqlite/) to implement our document store. UnQLite does not provide quite the functionality that we need, so we need to implement a layer on top of it that will be an adapter.

We want to be able to:
* Create named persistent collections of JSON objects.
* Configure a named collection have named indexes. Each index will used named fields of JSON object as key values.
* Add a JSON object to a named collection, which will automatically add it to all of the named indexes for the collection. Conditionally including JSON objects in an index is out of scope.
* Given a named collection, a named index and the relevant key value(s) retrieve the corresponding JSON object. Searches for multiple JSON objects are out of scope.

Update and deletion of JSON objects is out of scope for this task.

What UnQLite gives us out of the box is:
* A key-value store that works with keys and values that are arrays of bytes.
* A scripting language named Jx9 that provides part of a document store on top of the key-value store. It allows us to store records whose value is a given JSON object and whose key is a generated `u64` value.
* The ability to access the JSON objects in a collection, but no indexing capability.
* The ability to use the key associated with a JSON object to retrieve it.

Not the there is no built-in indexing mechanism. We will need to build an indexing mechanism that uses supplementary
key-value collection as indexes to map index keys to JSON record keys. 

# The Task
This task consists of these steps:
* Define a Rust struct named `json_collection_descr` that describes a JSON collection and its named indexes. It must describe the field names that contain the key value(s) for each named index.

* Define a Rust trait that defines methods to do the following things without in any way depending on using UnQLite for an implementation. We may decide on a different implementation in the future. 
  - Create an empty collection of JSON objects given a name and a `json_collection_descr`.
  - Add a JSON object to a named collection and update the named indexes as an atomic transaction. Either the JSON object is added to the collection and it is included in the indexes or none of that happens. <br>For now, we will treat all fields used for indexes as required. If they are missing or null we just reject the JSON object.
  - Given the name of a collection, the name of one of its indexes and a key value(s) retrieve the corresponding JSON object.

* Create an implementation of the rust trait that uses UnQLite.

# Completion Criteria
This task will be considered complete when:
* The code for this is in a new git repo named pyrsia-document-store.
* The implementation of the trait passes a set of unit tests.
* The implementation is available in a Rust crate.
* The crate is successfully included as a dependency in the node build in the sandbox repo.

# Related issues
Issue pyrsia/pyrsia-documentation#37 covers the update and delete operations that are out of scope for this task.

**Comment by mgrand** [comment]
@tiainen @johanvos @erwin1 I have asked a few times that you write comments in the code describing what each public method does. One of the benefits of doing this is that it would have become clearer to me that you did not quite understand what is supposed to happen. To clarify here is is a detailed description of how it should work in the context of a use case.

__Create a Collection__
We want to create a collection to contain metadata about packages. Packages will need to be found in at least two different ways. We will want to look them up by package type, namespace and package name. We will also want to look them up by their unique id.

To create this collection, it will need to have a name and two indexes, one for each of the different ways we want to find packages. Note that one of the indexes will be based on the values of three different fields in the records.

Assume that there is an `enum` defined like this:
```
enum SortOrder {
    ASCENDING,  // If an index is specified with this, fetching a range of values using the index should return
                // the lowest value first and the highest value last.
    DESCENDING, // If an index is specified with this, fetching a range of value using the index should return
                // the highest value first and the lowest value last.
}
```
and a struct defined like this:
```
struct IndexSpec {
    index_name: &str,  // the name of the index
    field_names: Vec<&str>, // The names of the fields that the index will be based on, from most significant
                            //  to least significant with respect to the sort order.
    direction: SortOrder,
}
```
To create the package collection we should have to write something like this:
```
let collection_name = "package";
let indexes = vec![IndexSpec{index_name: "keys",
                             field_names: vec!["packageType","namespace","packageName"],
                             direction: SortOrder::ASCENDING},
                   IndexSpec{index_name: "id",
                             field_names: vec!["id"],
                             direction: SortOrder::ASCENDING}];
document_store::create_collection(collection_name, indexes);
```

This call will create an UnQLite KV store with the same name as the collection name. It will store a single record in the store whose key will begin with a distinguished byte value that indicates it is the catalog record. There will be only one catalog record in each collection. The distinguished byte value will be the entire key.

The catalog record will be associated with a `u16` for each index that will serve as the index identifer. This index identifier will serve to identify keys associated with the index in the key value store. This is further explained below under the heading of __Insert a Record__.

__Open a Collection__
To begin working with a collection, we will write code like this:
```
let package_collection: document_store::Collection = document_store::open_collection("package");
```
We can then call methods of `package_collection` to work with the contents of the collection.

The `open_collection` method will read the contents of the catalog record so that `package_collection` knows the KV store to work with and what its indexes are.

__Insert a Record in a Collection__
To insert a record in the package collection, we should be able to write something like this:
```
json_string: &str = ...; // where the elipsis is replaced by a valid JSON string.
package_collection.insert(json_string)?;
```
The `insert` method
1. Parses the json string. If parsing fails, return an error.
2. We want to store only JSON objects. If the result of parsing determines that the JSON is not an object but an array, string, number, boolean or null then return an error. For reasons mentioned below, if the JSON string contains the unicode character \uffff also return an error
3. Determine if the object has all of the fields that the collection's indexes require for their keys. In the case of the package collection, the required fields are `packageType`, `namespace`, `packageName` and `id`. If any of these required fields are missing, return an error.
4. Start an UnQLite transaction on the KV store that contains the package collection.
5. Generate a random u128 value. Prefix it with a distinguished byte value that will identify it as the key of a JSON record.
6. Do an UnQLite fetch to verify that no record with the generated key already exists. If such a key already exists in the database, go back to the previous step to generate a new key for the JSON record.
7. Store a record in the KV store with the generated key and the JSON string as its value. If this returns an error roll back the transaction and return an error.
8. For each index defined for the collection (two are defined for the `package` collection) do this:
   a. From the fields require for the index we are working on, assemble a key value for the index. The key will consist of a distinguished byte value identifying the key as an index key. The distinguished byte value is followed by a `u16` that contains the index identier that identified the index. The index identifier is followed by the fields values in the order specified for the index. This must be done in a way that allows multiple indexes to share field values. <br>The field values must be separated in the key by a \uffff character. This is to avoid the case where there are two records with similar value in different fields generate the same index key. For example, if a key contains the values of fields named `a` and `b`, we want these two JSON strings to have different keys:<br>
       `{"a":"xy","b":"z"}`<br>
       `{"a":"x","b":"yz"}`
   b. Store a record in the KV store with the constructed index key as its key and the JSON record key generated in step 5 as its value. If this returns an error, roll back the transaction and return and error.
9. Commit the transaction.
10. Return success.


__Fetch a Record From a Collection__
To fetch a record from a collection, we should be able to write code like this:
```
let index_name = "keys";
let key_values = HashMap::new();
key_value.insert("packageType".to_string(), "docker".to_string());
key_value.insert("namespace".to_string(), "docker".to_string());
key_value.insert("packageName".to_string(), "Alpine".to_string());
let json_string: Option<&str> = package_collection.fetch(index_name, key_values);
```
The `fetch` method will:
1. Find the index identifier of the named index. If there is no such named index for the collection, it returns an error.
2. Construct the key of the index record to be fetched. If values for any of the fields associated with the index are not specified in the HashMap, return an error.
3. Fetch the index record from the KV store. If the record is not found return Ok(None).
4. Take the value of the fetched index record and use it to fetch the JSON record. If the JSON record is not found, log an ERROR and return Ok(None).
5. Return the value of the JSON record.

**Comment by johanvos** [comment]
@mgrand There is no PR associated with this issue, so I don't know what you are talking about.

**Comment by mgrand** [comment]
@johanvos This is where Joeri suggested in put this information. This is the more detailed specification for what the document store layer should do, not matter how you divide it into PRs.  I wrote this because Joeri asked for clarification. It seemed clear that the original higher-level specification I wrote was not detailed enough.
