### ISSUE TITLE
Define transactions for managing authorities

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#401]
Basic struct definition with a "name" and "public key" to uniquely identify and verify respectively

- [x] `TransactionType` #461 
TBA

***

## Background

We are using Aleph #322 with a Proof-of-Authority model. These "authorities", those participating in the consensus, will be recorded on the blockchain.

These will be entered a transaction.

**Comment by chb0github** [comment]
Transaction type: `AddAuthority`
Transaction type: `RevokeAuthority`

Need to add specific APIs for this functionality as they are core to the blockchain

**Comment by prince-chrismc** [comment]
This https://github.com/pyrsia/pyrsia/issues/401#issuecomment-1063117872 is actually the scope of #403 so this was completed with #461
