### ISSUE TITLE
Add authority for development to "Genesis Block"

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#402]
### Context

Genesis Block === Block 0

- [x] This is blocked by https://github.com/pyrsia/pyrsia/issues/401
- [x] This is blocked by https://github.com/pyrsia/pyrsia/issues/475

- hardcode the public key to the Genesis block in "add authority transaction" #401
- Save Keys somewhere (Git/Google/Slack/Neptune (yes the planet))

Currently we are only supporting Edward's keys #475, we will generate a pair and save it somewhere so everyone can run the example "blockchain node" and easily publish block as that root trust anchor to kick start new blockchains.

https://github.com/pyrsia/pyrsia/blob/95badf1e55c4373e4dee184ac2f64debcca68d41/src/blockchain/src/blockchain.rs#L104-L107

**Comment by fishseabowl** [comment]
Suppressed by the latest [architecture documentation](https://github.com/pyrsia/pyrsia/blob/main/docs/developers/pyrsia-architecture-and-use-cases.md)
