### ISSUE TITLE
Support adding and revoking authority transactions on the blockchain

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#403]
This needs https://github.com/pyrsia/pyrsia/issues/402
Depends on https://github.com/pyrsia/pyrsia/issues/401#issuecomment-1063117872

### Context

We recently added 

https://github.com/pyrsia/pyrsia/blob/95badf1e55c4373e4dee184ac2f64debcca68d41/src/blockchain/src/block.rs#L27-L33

### Goal

Support the innerworks of the blockchain

1. Adding a new signing key 
   - (which is an authority)
3. Revoking a Key
    4. needs a new transactions 
5. Can always revoke (even genesis)

Listing keys is out of scope, the abstraction of the datastore mean the caller of blockchain is responsible for this.

**Comment by prince-chrismc** [comment]
Should be followed up and correct by #408

**Comment by fishseabowl** [comment]
It was superseded by issue #780.
