### ISSUE TITLE
Define the validation process of authority transactions

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#408]
depends on by #403 

"Does the transaction make sense?"

- [ ] is the signature valid
- [ ] make sure authority exists before revoking
- [ ] don't allow duplicated "names"
- [ ] only accept transactions from "valid" authorities
- [ ] allows have at least one valid

Optional:

- add/update after a revoke

### Outstanding future questions

How do we look at certificates, expiration, etc...

**Comment by betarelease** [comment]
this seems old and outdated. @fishseabowl can you confirm if this is still relevant and please add context if we need to work on this. Otherwise please close.

**Comment by fishseabowl** [comment]
This is outdated
