### ISSUE TITLE
Improve the Blockchain API for "authority transactions"

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#409]
Partially implemented by https://github.com/pyrsia/pyrsia/issues/403 which is the base layer internal workings of the blockchain

### Goal

We need to support new "API level" transactions for the blockchain crate.

***

Who ever write this does what they like 🚀 for theimplementationn.... but conceptually we see two paths

- `enum` Transactions with "AddAuthority" and "RevokeAuthority" tuples
- implementation of `submit_new_transactions` can match on enum type
   - each on can be a private method to support each type if special processing is required

or

- Method for each type of transaction `submit_new_add_authority_transaction` etc.

### Vision/Idea

By API level, we mean it's support by the class for #321 

```rust
let chain = Blockchain::new();
// This is the new stuff we want to do
let add_transaction = blockchain::AddTransaction::new(....);
chain.submit_new_transaction(add_transaction, ...);
```

We expect this to be implemented in https://github.com/pyrsia/pyrsia/blob/main/src/blockchain/examples/simple_node.rs#L47

***

Limited focus for "authority" transactions supported in #403 

build on #408 maybe?

**Comment by fishseabowl** [comment]
Suppressed by [latest architecture documentation](https://github.com/pyrsia/pyrsia/blob/main/docs/developers/pyrsia-architecture-and-use-cases.md)
