### ISSUE TITLE
Developer setup guide is missing some details

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#410]
Extra information is required for the setup/installation to work

- [ ] Config docker daemon settings https://github.com/pyrsia/pyrsia/pull/370#discussion_r813213948
- [ ] `PYRSIA_ARTIFACT_PATH` can be configured https://github.com/pyrsia/pyrsia/pull/370#discussion_r814300380

**Comment by prince-chrismc** [comment]
related to #699

**Comment by betarelease** [comment]
Outdated. Closing.
