### ISSUE TITLE
Setup Central node in the Cloud

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#411]
Central nodes will be used to bootstrap the network and will be always available for new peer nodes to connect.

Central nodes will need:
1. Dockerized version of pyrsia node
2. Kubernetes deployment of these pyrsia node so that it can scale and autoheal
3. A mechanism to store the blockchain
4. A mechanism to prove the commit capability to Blockchain

**Comment by erwin1** [comment]
partly depends on #444 if we want this central node to be doing something useful.
There's already a PR for this #477 so I propose to setup this node as soon as this is merged.

**Comment by sbtaylor15** [comment]
pysria node running on GCP.  ip address is 34.71.47.224.  Retired the synapse instance and created a pyrsia only one.

@betarelease @prince-chrismc - Please update the Pyrsia DNS to point to 34.71.47.224.

**Comment by sbtaylor15** [comment]
We have pyrsia.link and pyrsia.io domains.

**Comment by erwin1** [comment]
The first use-case for this will be #364 to use this address as a p2p boot node, so I think a subdomain `boot.pyrsia.link` pointing to this IP would be nice.

**Comment by sbtaylor15** [comment]
@erwin1 right now we are using 7888.  So we need another one for p2p?
