### ISSUE TITLE
Add a "precommit" script for new contributes to easily prep PRs

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#437]
### Suggestion details

The goal is to write a small shell script that will run the basic `cargo` commands

- fmt
- build
- test

are the minimum set for CI to pass

### Additional details

additionally we may want to check if the correct tools are available

we should look for

- rustfmt (cargo-fmt) on the PATH
- restsec's audit (cargo-audit)
- clippy

Before running those commands

**Comment by AbhijithGanesh** [comment]
I'd like to work on this issue.

**Comment by prince-chrismc** [comment]
This should also note the script in the new docs from https://github.com/pyrsia/pyrsia/pull/430
