### ISSUE TITLE
Move local storage methods to blockchain example node

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#454]
We need to figure out where do the blockchain raw data saved in the node.
1. In memory
2. In files:  .pyrsia/blocks/blk*.dat
3. In DB

**Comment by fishseabowl** [comment]
I suggest storing the blockchain raw data in memory and in files at the moment.

**Comment by AbhijithGanesh** [comment]
We have to keep the blockchain light right? If that is the caes, I think In memory is the best option

**Comment by prince-chrismc** [comment]
Is this not why we made a [`DocumentStore`](https://github.com/pyrsia/pyrsia/blob/1126eb8504aca1f27ca45a0d6b643eb88296d312/src/document_store/document_store.rs#L68)

The crate for accessing the network and performing consensus was intended to match the existing code base 🤔 

Perhaps I misunderstood the issue?

**Comment by fishseabowl** [comment]
Sorry for the confusion. I mean what is the physical location of the blockchain. For this issue, the DocumentStore using UnQLite database engine is a bit heavy.

**Comment by prince-chrismc** [comment]
This is a duplicate!
#422

Covers this already
