### ISSUE TITLE
Expand installers to support MacOS and Windows platforms

### ISSUE THREAD

**Issue by AbhijithGanesh** [pyrsia/pyrsia#457]
### Suggestion details

Pyrsia is currently compiled and we utilize it through the target build.

I'd like to propose a script/MSI package/Mac Equivalent that'd simplify the installation process once we start releasing stable versions. This would make our project more complete as it'd improve the dev-ex. We can do this for any release/build version but it'd be more appropriate for stable releases. It make the Pyrsia tool better as it'd improve simplicity.

**Comment by sbtaylor15** [comment]
@AbhijithGanesh we are currently building installers for only Ubuntu.  The install can be done using a single command `curl -sSL https://pysria.io/install.sh | sh`. 

We will need installers for OS/X (brew) and Windows.  Windows will be the difficult one with the dependency on openssl.

**Comment by AbhijithGanesh** [comment]
I think in one of the prior meetings, @prince-chrismc had told us that the open-ssl dep would no longer be needed as libp2p takes care of it in someway, I am not sure about it. I'd like to have more research

**Comment by prince-chrismc** [comment]
_could be replaced_ it's an open point of discussion in #181

**Comment by AbhijithGanesh** [comment]
I think it'd be great to remove OpenSSL

**Comment by betarelease** [comment]
I created smaller tickets for this

#1010  - Mac Intel
#1012  - Mac M1
#1011 - Windows

**Comment by betarelease** [comment]
This is now split into the above tickets and will be prioritize as separate efforts. So closing this issue.
