### ISSUE TITLE
Readme needs to be updated with updated format of CLI

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#460]
This came up a few times in PRs and I noticed it again.

https://github.com/pyrsia/pyrsia#connecting-with-other-nodes 

> Total Disk Available:    983112

**Comment by MitaliBo** [comment]
@prince-chrismc that is from the initial draft when that value was harcoded in the code but cli config has changed and it recognizes units and calculate based on that, cli has the command to configure your local total disk. so we need to update readme i guess.

pyrsia node -s
Connected Peers Count:       1
Artifacts Count:             1
Total Disk Space Allocated:  10.84 GB
Disk Space Used:             0.0260%

I am changing this issue name to update readme
