### ISSUE TITLE
Load Central Node with offical docker images

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#467]
### Suggestion details

A script is needed to pull the official docker images into the central node.  The script should be run hourly creating a cache of the official images in Pyrsia.  Down the road, other methods such, as webhooks, could be used to trigger instead of being scheduled.

Need mechanism to have CLI consume docker node api's to fetch manifest and recusively fetch all layers of image, given an imageName and tag.

### Additional details

Need to decide if we want to include Verified Images.

**Comment by sbtaylor15** [comment]
Added cron job to loop through the official docker images and perform a `docker pull <image>:<tag>` while running on GCP that has pyrsia installed.  The job runs at noon and midnight.  Images that have not changed are not pulled a second time by docker and pyrsia.

**Comment by sbtaylor15** [comment]
#538 is needed to load all official images.  The expanding of the images is causing the script to run for days.

**Comment by betarelease** [comment]
Dependent on changes to the pyrsia cli - cli needs to download images without expanding. @MitaliBo @erwin1

**Comment by sbtaylor15** [comment]
Moved the docker /var/lib/docker/overlay2, /var/lib/docker/tmp and /var/lib/docker/image directories to point to RAM disk for speed.  Using RAM disk enabled the loading to finish in a day even with the expansion still taking place.
