### ISSUE TITLE
A Pyrsia node must try to restore its p2p connection(s)

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#469]
Current situation:
a node is started with `--peer` option (e.g. could be a central node) after which the node connects to more peers.

When a peer goes down (or is restarted), that lost connection should be tried to be re-established.

steps to reproduce:
- start node1 p2p listening on 44000
- pull any artifact from node1
- start node2 p2p dialing to node1:44000
- restart node1
- pull the same artifact from node2

Expected: node2 finds the artifact in the p2p netwerk (on node1) 

Instead: it doesn't seem to be connected to node1 anymore

**Comment by tiainen** [comment]
This works out of the box, if `node1` is setup to always use the same keypair to determine the peer ID. If a new peer ID is used each time, `node2` will log the following error event when trying to dial `node1`:

```
OutgoingConnectionError {
    peer_id: Some(PeerId("12D3KooWBJTjFrqJCacnb72wUfuM6xevQZYKcjFTN3yp4V4nMss1")),
    error: WrongPeerId {
        obtained: PeerId("12D3KooWQjAnm8xUyLk5Uj2wfQYv68MW7U4Kk8VpwTMmCepSULCA"),
        endpoint: Dialer {
            address: "/ip4/127.0.0.1/tcp/44000/p2p/12D3KooWBJTjFrqJCacnb72wUfuM6xevQZYKcjFTN3yp4V4nMss1",
            role_override: Dialer
        }
    }
}
```

The solution is thus to make the peer ID persistent. This immediately also answers #505.

**Comment by tiainen** [comment]
Fixed with https://github.com/pyrsia/pyrsia/pull/539.
