### ISSUE TITLE
Further changes to block structures to clarify the many structures

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#473]
### Background

While reviewing code for #413 "documente block structures", it was noted that several data elements could use some light refactoring

Probably a good idea to revamp the whole [`block.rs`](https://github.com/pyrsia/pyrsia/blob/main/src/blockchain/src/block.rs) to break it into into separate modules under `structures/`.

These are the items we need to address:

- [x]  ~remove transactions_root from block header - pre-optimization~
- [x]  rename `transaction.transaction_hash` to `hash`
- [x]  rename `transaction.trans_type` to `type_id`
- [x]  hashes and signatures should be private and only accessible by api as `get`
- [x]  merge method `new_block` with `Block::new`
- [x] Remove `PartialTransaction` 

***

May of which are related to  

https://github.com/pyrsia/pyrsia/blob/95badf1e55c4373e4dee184ac2f64debcca68d41/src/blockchain/src/block.rs#L80-L88

### Future Work

- https://github.com/pyrsia/pyrsia/issues/473#issuecomment-1062288296

**Comment by prince-chrismc** [comment]
Open point is cutting the "partial" structs.
They currently provide no benefit but might be costly to slash

**Comment by prince-chrismc** [comment]
We noticed the `transaction_root` was actually being used and it's required for the integrity of the blockchain, without it the transactions are not covered

My understanding was that it was not being used, since it's was hidden within the `PartialTransaction`
