### ISSUE TITLE
Simplify blockchain example to only use Edward's keys

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#475]
Simplify blockchain example to only use Edward's keys

_Originally posted by @prince-chrismc in https://github.com/pyrsia/pyrsia/pull/461#discussion_r822127103_

### Context

Summary is here https://github.com/pyrsia/pyrsia/issues/475#issuecomment-1063098820

https://github.com/pyrsia/pyrsia/blob/95badf1e55c4373e4dee184ac2f64debcca68d41/src/blockchain/examples/simple_node.rs#L66-L70

### Goal

We should  only use ` identity::Keypair::Ed25519`

**Comment by prince-chrismc** [comment]
https://github.com/pyrsia/pyrsia/blob/95badf1e55c4373e4dee184ac2f64debcca68d41/src/blockchain/examples/simple_node.rs#L66

**Comment by chb0github** [comment]
We are only going to be using 1 set of keys/type -right now the code tries to match amongst 3 types, and only 1 of the match yields a result.

**Comment by prince-chrismc** [comment]
Closed #423 since it was less complete this is the good issue
