### ISSUE TITLE
Delete branch workflow does not work as intented

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#478]
This was called out on Slack by @erwin1 

https://openssf.slack.com/archives/C0302CVKPA5/p1646764526086929
https://openssf.slack.com/archives/C0302CVKPA5/p1646765025125879?thread_ts=1646764526.086929&cid=C0302CVKPA5

> I was looking into this PR https://github.com/pyrsia/pyrsia/pull/470
and since this was started from a fork, this workflow https://github.com/pyrsia/pyrsia/actions/runs/1948192862/workflow should’ve removed that branch, no? it seems to have run even https://github.com/pyrsia/pyrsia/runs/5456070351?check_suite_focus=true and didn’t fail

> seems like `/git/refs/heads/${{ github.ref }}` should just be `/${{ github.ref }}` on https://github.com/pyrsia/pyrsia/actions/runs/1948192862/workflow#L13

**Comment by betarelease** [comment]
These workflows are no longer used. so we can safely close this.
