### ISSUE TITLE
Investigate what the keys are used for in the artifact manager and what the use is of the kademlia proxy.

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#482]
I noticed we are generating keypairs and peer ids in two places, raised it on [Slack](https://openssf.slack.com/archives/C0302CVKPA5/p1646860564771849) and it seems to be worth looking into.

https://github.com/pyrsia/pyrsia/blob/11e1d1399951ffa2953e01b8df4c1022f3471a80/src/network/p2p.rs#L42

and 

https://github.com/pyrsia/pyrsia/blob/17c5d20f665213cf727410a9d4182a36859596bd/src/node_manager/handlers.rs#L39

//cc @tiainen

**Comment by fishseabowl** [comment]
Also we should store the Keypair to a local file(./pyrsia/keys). Otherwise, when a node restarts, it will generate a new PeerID.

**Comment by tiainen** [comment]
> Also we should store the Keypair to a local file(./pyrsia/keys). Otherwise, when a node restarts, it will generate a new PeerID.

@fishseabowl I've created #505 for this.
