### ISSUE TITLE
Remove all program references to OpenSSL

### ISSUE THREAD

**Issue by AbhijithGanesh** [pyrsia/pyrsia#484]
### Suggestion details

All files involving the openssl crate needs to be refactored and modified accordingly.

**Comment by AbhijithGanesh** [comment]
Only `signed.rs` uses openssl right?

**Comment by fishseabowl** [comment]
At the moment, the blockchain uses libp2p hashing and encryption module.

**Comment by prince-chrismc** [comment]
This replaces https://github.com/pyrsia/pyrsia/issues/181
