### ISSUE TITLE
Refactor Blockchain::header::Address to libp2p::PeerId

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#486]
At the moment, blockchain module use self-defined Address structure as NodeID: https://github.com/pyrsia/pyrsia/blob/45d4c345d4b630c5d73ca3b51e3f5b6169c70057/src/blockchain/src/crypto/hash_algorithm.rs#L22-L25
https://github.com/pyrsia/pyrsia/blob/45d4c345d4b630c5d73ca3b51e3f5b6169c70057/src/blockchain/src/header.rs#L23

Pyrsia Node use libp2p::PeerId as NodeID

for consistency, refactor header::Address to libp2p::PeerId

**Comment by prince-chrismc** [comment]
This will be needed for #322 most likely

**Comment by prince-chrismc** [comment]
please follow up on https://github.com/pyrsia/pyrsia/pull/481#discussion_r826218072 🙏

**Comment by prince-chrismc** [comment]
Blocked by #481
