### ISSUE TITLE
Improve code coverage for new `storage/blobs.rs`

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#488]
https://github.com/pyrsia/pyrsia/pull/431 per this check 
https://github.com/pyrsia/pyrsia/pull/431/checks?check_run_id=5517289694

**Comment by dgarus** [comment]
@betarelease hi!
Is this issue still actual?
I went to the link from the issue description and found out that a problem file was `src/docker/v2/storage/blobs.rs`.
But now there is no this file on the main brunch..

**Comment by betarelease** [comment]
@dgarus Thanks for pointing this out. I think this got outdated too.
