### ISSUE TITLE
pyrsia --version is missing the build number.

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#490]
### Steps taken/Steps to reproduce

`pyrsia -version`

```
root@pyrsia-node-1:/usr/local/bin# pyrsia --version
pyrsia_cli 0.1.0
```

### Expected Behavior

The version number is updated in the Cargo.toml as part of the build with the build number.  The full version with the build number should be displayed as part of the --version output.

### Experienced Instance of the bug

20.04.3-Ubuntu
Latest version from apt-get repo

**Comment by efrisch** [comment]
@sbtaylor15 I've updated the code to report the version as the git sha hash. Now, I'm second guessing myself - do we want a more complex string? Maybe something like

pyrsia_cli 0.1.0 (adc77562a990a0c5c5b0d79db4e5f21709252183)

Where 0.1.0 comes from the Cargo.toml and adc77562a990a0c5c5b0d79db4e5f21709252183 is the git hash?

**Comment by sbtaylor15** [comment]
@efrisch That should work.  I don't think we need to get more complicated than that.  We will eventually need to generate a SPDX SBOM for the code as part of the build and that SBOM will contain deeper info about what we created.
