### ISSUE TITLE
Assign ip addr to boot.pyrsia.link

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#497]
GCP VM instance (central node) has static ip of 34.71.47.224 that needs to be assigned to boot.pyrsia.link

**Comment by prince-chrismc** [comment]
Oh I put `bootstrap` I did not know it changed

![image](https://user-images.githubusercontent.com/16867443/159053208-4733924c-d45e-4901-a082-e0949f251901.png)

**Comment by sbtaylor15** [comment]
@prince-chrismc here is the [link](https://docs.google.com/document/d/1mOSMyZkM-HaKYnKNwk_Qr6t3331EZXHSQgp2L8dsjw4/edit) to the decision for boot.pyrsia.link

**Comment by prince-chrismc** [comment]
![image](https://user-images.githubusercontent.com/16867443/159373962-0b546f33-14f1-45aa-ae6a-ec15cfd34322.png)

The conversation in that meeting was confusing. It should be correct now.
