### ISSUE TITLE
Declaring `extern crate` should no longer be needed

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#502]
Declaring `extern crate` should [no longer be needed](https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html#no-more-extern-crate). Defining it in `Cargo.toml` is sufficient.

_Originally posted by @tiainen in https://github.com/pyrsia/pyrsia/pull/494#r829363071_

**Comment by fishseabowl** [comment]
[https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html](url)

**Comment by AbhijithGanesh** [comment]
We can clean all extern crates then.

**Comment by betarelease** [comment]
Just clean up code wherever `extern` is used and submit a PR

**Comment by AbhijithGanesh** [comment]
@prince-chrismc I am working on  this! Please assign it to me :)!
