### ISSUE TITLE
Persist the generated libp2p keypair

### ISSUE THREAD

**Issue by tiainen** [pyrsia/pyrsia#505]
At the moment, a private/public ed25519 keypair is generated that is used as the PeerId within the libp2p network. However, the PeerId is regenerated each time the pyrsia node is started.

Investigate if there is a good reason to persist the generated keypair and reload it during consecutive launches of the pyrsia node.

**Comment by betarelease** [comment]
Blockchain needs the PeerID.

**Comment by tiainen** [comment]
When reading a bit about peer identity ([Peer Identity](https://docs.libp2p.io/concepts/peer-id/) and [Addressing](https://docs.libp2p.io/concepts/addressing/)), it seems useful to have a persistent PeerId that can be passed in when dialing:

> Now [not only do] my friends know where to find me, anyone they give that address to can verify that the machine on the other side is really me, or at least, that they control the private key for my PeerId.
