### ISSUE TITLE
remove OpenSSL from deployment - since Openssl has been removed from the codebase now

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#507]
This came up during the PR for removing OpenSSL was being discussed. Also was an action item from our Retro to ensure we do not forget to remove this from deployments.

Related issue #494

**Comment by prince-chrismc** [comment]
I was under the impression #494 was already doing this 🤔 there are no other references (in the repo) to openssl after with exception to the `Cargo.lock`
