### ISSUE TITLE
As a user I want to get an updated docker client that can interact with pyrsia So that my workflows for CI do not change.

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#53]
As a user I want to get an updated docker client that can interact with pyrsia So that my workflows for CI do not change. The docker client should interact with a docker integration that is part of the Pyrsia node. The docker integration should implement the docker v2 API and be based on the node manager's API that provides common operations for supporting many kinds of artifacts.

**Comment by erwin1** [comment]
in #69 it was decided to use this approach:

 - use the pull-through cache for docker pull
 - have a lazy pull mechanism in Pyrsia node that will pull from Docker Hub and publish in the Pyrsia network
 - do not directly docker push to Pyrsia, but instead rely on pushing to Docker Hub

I've created #123 and #124 as follow-ups (and also #122 probably for after demo) and there will be no need for any changes in the docker client code, so I'm closing this.
