### ISSUE TITLE
Refactor add_block, get_latest_block and some test codes on blockchain

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#534]
add_block method add a new block to blockchain
get_latest_block method return the latest block data. 
```rust
impl Chain {
   pub fn add_block(&self, &Block) {}
   pub fn get_latest_block(&self) ->&Block {
   }
}
```
blocked by #535

**Comment by prince-chrismc** [comment]
This is tangled with #531

**Comment by fishseabowl** [comment]
We could create a PR to cover these two issues.

**Comment by fishseabowl** [comment]
It's outdated. Related work has been completed.
