### ISSUE TITLE
Store docker manifests in Pyrsia network

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#540]
Since #363 docker images are requested from the p2p network if they are not locally available.
The same should also happen for the docker manifests that a docker client requests during a 'docker pull' 

These manifest are currently still handled as originally specified:
* retrieve locally
* retrieve from Docker Hub if not available locally

**Comment by tiainen** [comment]
I have split this issue up into some smaller parts:

- #622 
- #623 
- #624 
- #625
