### ISSUE TITLE
apt-get installer fails in docker build

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#557]
### Steps taken/Steps to reproduce

See [docker build log](https://github.com/pyrsia/pyrsia/runs/5811477736?check_suite_focus=true)
Also, @AbhijithGanesh has further details if needed.

### Expected Behavior

Pyrsia installed in docker image using apt-get and .deb

### Experienced Instance of the bug

Docker CI part of the build

**Comment by fishseabowl** [comment]
repo error?
#6 15.09 Err:2 https://pyrsia.io/repo focal/main amd64 pyrsia amd64 0.1.0+1256
#6 15.09   404  Not Found [IP: 185.199.109.153 443]

**Comment by sbtaylor15** [comment]
@fishseabowl the gh pages site is down for some reason or in the process of being updated.  Moving the repo off GH to GCS will fix this long term. #562
