### ISSUE TITLE
Add linting job for markdown files

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#580]
Looking over #541 I noticed a handful of issues that would have been caught by https://github.com/markdownlint/markdownlint
I think we are at the point that we should step quality checks here as well.

Similar to #479 and #577  this job should only run if `.md` files are changed

***

Quickly looking I found https://github.com/actionshub/markdownlint

and I also noticed https://github.com/gaurav-nelson/github-action-markdown-link-check which might be fun to toss in

**Comment by prince-chrismc** [comment]
@VitaliyaIoffe Would this be something you might be interested in helping with?

**Comment by VitaliyaIoffe** [comment]
@prince-chrismc yeap, please, assign this ticket to me
