### ISSUE TITLE
Get list of stored package versions in the metadata manager

### ISSUE THREAD

**Issue by tiainen** [pyrsia/pyrsia#586]
### Suggestion details

When a pyrsia node is started, it should provision all package versions that are already present in the metadata manager on the libp2p network. Currently, it is not possible to get a list of all package versions.

Add a new method to the metadata manager to allow listing all the stored package versions so that a pyrsia node is able to provision them. This is required to be able to complete #540.

**Comment by betarelease** [comment]
left it in triage since @johanvos and @erwin1 were out today. Lets add more context if needed
