### ISSUE TITLE
Incorrect error message from CLI running `pyrsia -l`

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#588]
When run pyrsia -l, get the below message:
```
./target/release/pyrsia -l 
Connected Peers:
[]
error: Please specify correct subcommand

USAGE:
    pyrsia_cli

For more information try --help
```

I guess the subcommand is not mandatory. it is better not to output error messages.

**Comment by prince-chrismc** [comment]
The usage is also a touch misleading since it add the `_cli` suffix
