### ISSUE TITLE
Explore: Refactor pyrsia cli command

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#594]
For better user experience, it is better to update Pyrsia cli command documentation and code.

Here are some confusing case and codes:
1. As mentioned by @tiainen  [I believe that the entire match above on Some(("node", ...) can be removed as well, since config is the only remaining subcommand](https://github.com/pyrsia/pyrsia/pull/590#discussion_r851185433)

2. Run  "pyrsia config -a"
    Output: USAGE: pyrsia_cli
![image](https://user-images.githubusercontent.com/19720920/163598605-96b1203b-e0d9-4010-bf8b-42dc294e005f.png)

3. Configuration parameters are not checked. I believe some ports are not available for Pyrsia nodes
![image](https://user-images.githubusercontent.com/19720920/163599109-d526ed18-de68-41db-930e-5550e995e65b.png)

**Comment by MitaliBo** [comment]
@fishseabowl on what basis we want to validate the config params , url and port can be anything
