### ISSUE TITLE
CLI builds on ubuntu do not successfully compile and execute

### ISSUE THREAD

**Issue by mseabornIBM** [pyrsia/pyrsia#599]
When building a `developer setup` on a clean Ubuntu VM (not the packaged installer for pyrsia)

### Steps taken/Steps to reproduce

1. Start from a clean build of ubuntu's latest OS
2. Download latest mainline branch "main" from Pyrsia
3. execute cargo build --workspace
4. executing cargo build --workspace after adding openssl dev and clang dev packages with apt install works after multiple calls to cargo build.
5. After cli successfully builds execute DEV_MODE=on RUST_LOG="pyrsia=debug,info"  ./pyrsia_node -H 0.0.0.0 -p 7888 -L /ip4/0.0.0.0/tcp/44001

### Expected Behavior

Successful build of the software.
Successful starting of the CLI.

### Experienced Instance of the bug

Had to install undocumented dependencies, clang and openssl
cli crashed with the following log
$ DEV_MODE=on RUST_LOG="pyrsia=debug,info"  ./pyrsia_node -H 0.0.0.0 -p 7888 -L /ip4/0.0.0.0/tcp/44001
 DEBUG pyrsia_node > Parse CLI arguments
 DEBUG pyrsia_node > Create p2p components
 WARN  pyrsia::util::keypair_util > Failed to persist newly generated keypair: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
 DEBUG pyrsia_node                > Start p2p event loop
 DEBUG pyrsia_node                > Setup HTTP server
 DEBUG pyrsia_node                > Pyrsia Docker Node will bind to host = 0.0.0.0, port = 7888
 DEBUG pyrsia_node                > Setup HTTP routing
 DEBUG pyrsia_node                > Setup HTTP server
 INFO  pyrsia_node                > Pyrsia Docker Node will start running on 0.0.0.0:7888
 DEBUG pyrsia_node                > Start p2p components
 DEBUG pyrsia::network::client    > p2p::Client::listen "/ip4/0.0.0.0/tcp/44001"
 DEBUG pyrsia_node                > Provide local artifacts
 ERROR pyrsia::node_manager::handlers > Error initializing Artifact Manager Directory, error is: Failed to create artifact manager directory in dev mode
thread 'main' panicked at 'Error initializing Artifact Manager Directory, error is: Failed to create artifact manager directory in dev mode', src/node_manager/handlers.rs:78:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 INFO  pyrsia::network::event_loop    > Local node is listening on "/ip4/127.0.0.1/tcp/44001/p2p/12D3KooWDTZxwB8AWjkfcTaVwvyUAqep1ZRBDL8fUi5oec5NKV2S"
 INFO  pyrsia::network::event_loop    > Local node is listening on "/ip4/172.17.0.1/tcp/44001/p2p/12D3KooWDTZxwB8AWjkfcTaVwvyUAqep1ZRBDL8fUi5oec5NKV2S"
 INFO  pyrsia::network::event_loop    > Local node is listening on "/ip4/192.168.1.24/tcp/44001/p2p/12D3KooWDTZxwB8AWjkfcTaVwvyUAqep1ZRBDL8fUi5oec5NKV2S"
 ERROR pyrsia::node_manager::handlers > Initialization of Artifact Manager Directory panicked!

**Comment by betarelease** [comment]
In order to build pyrsia_cli on a Ubuntu machine from the workspace we have a dependency on `openssl` and `clang`.

When installing pyrsia_cli from the installer - there is not dependency on `openssl`. Maybe there is a dependency on `clang`

When pyrsia_cli uses https it will need `openssl` in the future.

This nuance has not documented clearly.

**Comment by betarelease** [comment]
There are 3 issues noticed above. Split them into 3 tickets before trying to fix them.

**Comment by betarelease** [comment]
#515  Issue about Clang

**Comment by prince-chrismc** [comment]
@MitaliBo can you please look at the startup issue  when you get a chance, @mseabornIBM brought it up at standup
```
ERROR pyrsia::node_manager::handlers > Error initializing Artifact Manager Directory, error is: Failed to create artifact manager directory in dev mode
```

**Comment by AbhijithGanesh** [comment]
This issue has been patched!
