### ISSUE TITLE
Explore libp2p to evaluate if it  can be used as a stack to build file sharing for pyrsia network.

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#6]
From Mark Grand:
I don't think we need to be managing file storage, just file sharing. That is a simpler problem.

**Comment by prince-chrismc** [comment]
@efrisch is this done? since you looked into this topic and decided to go in a completely different direction?

**Comment by efrisch** [comment]
@Christopher McArthur ***@***.***>
I think it's reasonable to move it to "won't do" for now. I couldn't find
complete rust examples. But here's a WIP, for inquiring minds and to note
how we got here, https://github.com/mattsse/libp2p-bittorrent-protocol --
if there's enough time / interest perhaps we write our own bittorrent
client from scratch too.

In case we need to revisit this, I found another possible approach in go:
https://github.com/dennis-tra/pcp

Elliott

Elliott Frisch *|* Block Chain Developer *|* JFrog
Mobile: *+1.770.256.6094*

**Comment by prince-chrismc** [comment]
Awesome. Closing!
