### ISSUE TITLE
Move DNS from NameCheap to Google Cloud

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#617]
We use namecheap for domain names and use google cloud to host our cloud infrastructure. 

Currently we are using the DNS on the namecheap system to provision subdomains and manage DNS entries. 

We would like to move these entries to Google Cloud DNS so that we can manage all cloud infrastructure in one place and also if we move registrars we do not lose DNS entries

Reference article : https://www.wpmentor.com/setup-domain-google-cloud-platform/

**Comment by prince-chrismc** [comment]
> if we move registrars we do not lose DNS entries

There are a few "verified" domain settings that we will need to double check

**Comment by sbtaylor15** [comment]
Now using Google Cloud DNS for pyrsia.io and pyrsia.link.  Also, LFX has taken over domain ownership
