### ISSUE TITLE
Define the payload of a transaction

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#675]
Only the very minimal that is needed for the MVP use cases.

A block could look like this:
```
{
      "header": {
        "parent_hash": "sha3:",
        "ordinal": 1,
        "transactions_hash": "sha3:",
        "committer": "12D3KooWJ2kVem2md3XNbvuuT5prry92K63Ky2GFn58GqySVUanG",
        "timestamp": 1234576593,
        "none": 1234,
        "hash": "c0e71975e20f8a6"
      },
      "transactions": [
        {
          "type_id": "AddArtifact",
          "submitter": "12D3KooWJ2kVem2md3XNbvuuT5prry92K63Ky2GFn58GqySVUanG",
          "timestamp": 123456,
          "payload": {
      
          },
          "nonce": 12345,
          "hash": "sha3",
          "signature": "cc6fc43d73cf124c60ad"
        }
      ],
      "signature": "sha3:"
    }
```

But the only data the transparency log is interested in, is the **payload**. 
The payload is created by the Transparency log component at the time of an artefact publication. And it is read from the transaction index when an artefact has to be verified.

In MVP, the contents of the payload is defined as:
```
    "payload": {
       "operator":"AddArtifact",
       "artifact_id": "mChnVzIY1FylZoFEJgL4BbceCLEOYMqS"
       "hash": "RhBKQ9ndIaZUhXid0MWhPoAAeJPDzZQj..."
   }
```

Currently, the only supported operation is ‘AddArtifact’ but more operation types can of course be added later on.

**Comment by betarelease** [comment]
Can you verify if this is done already @tiainen ? @johanvos

**Comment by tiainen** [comment]
A first version has indeed been define with #722.
