### ISSUE TITLE
Define the blockchain API to add a new transaction

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#676]
This is entry point to the blockchain component from the transparency log in case of an artefact publication.

The transparency log component creates a payload and asks the blockchain component to store it as a transaction on the blockchain:

could be as simple as `add_transaction(payload, listener)`

Once this API is defined, the Transparency log component can be implemented.

(Arrow 7a - https://pyrsia.io/docs/developers/pyrsia-high-level-overview/)

**Comment by prince-chrismc** [comment]
Code is living in @chb0github fork waiting to be merged back

**Comment by fishseabowl** [comment]
Completed on #978
