### ISSUE TITLE
Implement block storage on filesystem

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#679]
The blockchain component itself will need access to stored blocks (e.g. to make them available in the p2p network). Therefore the Blockchain component itself will be responsible for storing blocks. 
Block will be stored on filesystem. 1 block = 1 json file.

The block storage itself is local to the blockchain component. It does not need an interface for use in other components.

(Arrow 11 in -https://pyrsia.io/docs/developers/pyrsia-high-level-overview/)

**Comment by fishseabowl** [comment]
Currently PR#1021 is a slightly different implementation that saves all blockchain data to a file, where each line is a block.
