### ISSUE TITLE
Explore docker integration options

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#69]
Following the discussion in #53, this is a subtask to investigate the 2 different options:

1. Change CLI to change resolution of pyrsia:// to localhost:/
2. use pull through cache https://docs.docker.com/registry/recipes/mirror/

**Comment by prince-chrismc** [comment]
@erwin1 Can this be closed?

**Comment by erwin1** [comment]
yes for future reference, I will be creating different issues.
this was the result of this analysis https://github.com/pyrsia/pyrsia-documentation/blob/main/docker-integration-analysis.md

**Comment by erwin1** [comment]
To record the decisions:

- use the pull-through cache for docker pull

- have a lazy pull mechanism in Pyrsia node that will pull from Docker Hub and publish in the Pyrsia network

- do not directly push to Pyrsia, but instead rely on pushing to Docker Hub
