### ISSUE TITLE
"Join Our Community" is floating between "Get Involved" and "Tutorials"; should be at bottom

### ISSUE THREAD

**Issue by efrisch** [pyrsia/pyrsia#690]
### Steps taken/Steps to reproduce

Visit web site https://pyrsia.io/docs/tutorials/quick-installation/

### Expected Behavior

"Join our community" at bottom. "Documentation Overview" at top.

### Experienced Instance of the bug

Browser

**Comment by prince-chrismc** [comment]
We need to revert #683  but thats blocked by https://github.com/pyrsia/pyrsia.github.io/issues/63 which will allow us to control the setting
