### ISSUE TITLE
MacOS Tutorial has outdated information 

### ISSUE THREAD

**Issue by prince-chrismc** [pyrsia/pyrsia#699]
### Configure Docker Desktop

https://pyrsia.io/docs/tutorials/setup_on_macosx/#configure-docker-desktop-to-use-node-a-as-registry-mirror

Did not clear state where to to add the configuration and I needed to look up https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

We should provide an example 

It also did not tell me how to get my local IP

### Does not document how to clean up the system afterwards

So I can repeat the demo!

### Related issues

#410

**Comment by prince-chrismc** [comment]
Default docker settings st v20.10

```json
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```

**Comment by prince-chrismc** [comment]
#718 addressed a handful of issues

**Comment by betarelease** [comment]
Closing this since the PR captured many of the issues. For anything new create another issue.
