### ISSUE TITLE
node fails and then wont start back up

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#701]
### Steps taken/Steps to reproduce

First error:

![image](https://user-images.githubusercontent.com/14826572/168683690-1aa4860b-0725-4836-b462-293bd1d040c4.png)

Second error on restart:

![image](https://user-images.githubusercontent.com/14826572/168683748-0ccba939-2cf0-4e78-97b6-8754a0b6a257.png)

# Steps to reproduce

Run the following script to start loading in the official docker images.  _**Set UNAME and UPASS to valid values.**_ The first error happens when you have about 780 files in the artifact manager file system.  The second error happens when you try restarting pyrsia.

```
#!/usr/bin/env bash

# Example for the Docker Hub V2 API
# Returns all images and tags associated with a Docker Hub organization account.
# Requires 'jq': https://stedolan.github.io/jq/

# set username, password, and organization
UNAME="pyrsiaoss"
UPASS="XXXXXX"
ORG="library"

# set -e

# get token
TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${UNAME}'", "password": "'${UPASS}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

# get list of repositories
next="https://hub.docker.com/v2/repositories/${ORG}/?page_size=100"

while [ "$next" != "" ]; do
    curl -s -H "Authorization: JWT ${TOKEN}" ${next} > /tmp/out.json
    REPO_LIST=$(cat /tmp/out.json | jq -r '.results|.[]|.name')
    next=$(cat /tmp/out.json | jq -r '.next')

    # output images & tags
    for i in ${REPO_LIST}
    do
    # tags
    IMAGE_TAGS=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${ORG}/${i}/tags/?page_size=100 | jq -r '.results|.[]|.name')
    for j in ${IMAGE_TAGS}
    do
        docker pull ${i}:${j}
        docker images -q | xargs docker rmi
    done
    done
done
```

### Expected Behavior

Artifacts to continue to be added to the artifact manager file system.

### Experienced Instance of the bug

OS: Ubuntu Focal
Pyrsia Version: 0.1.0+1537

**Comment by betarelease** [comment]
This is a blocker for [#467](https://github.com/pyrsia/pyrsia/issues/467) @tiainen @erwin1 appreciate it if you can look at it in the morning and let us know what needs to be done for a fix.

**Comment by erwin1** [comment]
1. The first error is a network error and a panic as a result. It seems natural that such errors can happen, so we will make changes to prevent the panic and propagate the error. 
We have a hard time reproducing this error though, because we hit docker API limits before we hit this error. These API limits are very specific to the 'central node', regular nodes won't be requesting all official docker images at once.

2. This error happens when booting up a Pyrsia node that already has a lot of local artifacts and hits a default limit in the p2p settings. We will make this setting adjustable to it can be increased on the central node.

**Comment by sbtaylor15** [comment]
@erwin1 using a valid userid and password for the authentication seems to get around the dockerhub rate limiting and minimizes errors.

**Comment by erwin1** [comment]
After ~200 pulls using a free, authenticated user I got:
```
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

which seems to be in line with this:
```
The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.
```

In any case, if it doesn't happen on the central node, that's fine.
