### ISSUE TITLE
AutoNAT protocol implementation

### ISSUE THREAD

**Issue by MitaliBo** [pyrsia/pyrsia#711]
AutoNAT protocol helps to define if a node is behind the NAT or not. As of now we are assuming that every node is behind the NAT and so they are connected with relay first and attempt to hole punch for NAT Traversal

**Comment by betarelease** [comment]
Is this the same as your PR for autoNAT? @efrisch

**Comment by efrisch** [comment]
> Is this the same as your PR for autoNAT? @efrisch

@betarelease Yes. https://github.com/pyrsia/pyrsia/pull/848

**Comment by betarelease** [comment]
Also is this the same as #584? Can we close one of them?
