### ISSUE TITLE
Block data must save immediately and not just on app exit

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#728]
### Suggestion details

Currently, when block data is saved, the actual file is not written to disk until the app exits. This prevents useful debug from occurring

**Comment by betarelease** [comment]
This was seen on an isolated branch. 
Currently we do not save yet and there is another issue that tracks how the data gets saved to the file system.

**Comment by fishseabowl** [comment]
Suppressed by issue #679
