### ISSUE TITLE
Blocks and Transactions must be ordered, and unique 

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#729]
### Suggestion details

There is much about blocks and transactions that either bluntly requires them to be unique, collectively, as well as have a ordering. Currently, blocks and transactions lack several key features that allows this

Colloquially, it's expected that blocks and transactions always maintain their "order" - to most this means a time ordering, but as this is supposed to be a distrubuted system, and time ordering will be tricky since each node may have a different understanding of the current time without persistent synchronization through something like NTP

### Additional details

Specifically needing to be done:
### Blocks
1. Blocks in the blockchain must be maintained in a Set (to ensure transitive uniqueness). They are currently in a `Vec`
2. Blocks must be sortable, at a minimum (and perhaps maximum) by `ordinal`. Perhaps by timestamp? 

Meeting objectives 1, and 2 can probably be done using a `BTreeSet`

### Transactions
1. Must be sortable, relative to the block they are in. As each node is responsible for creating a block and it's transactions, a sort by timestamp should suffice without having to manage an ordinal, although an ordinal would be visually easier to understand
2. Transactions must also be in a `Set` to prevent any unwanted duplicate insertions

**Comment by fishseabowl** [comment]
Blocks are always ordered and unique, which is guaranteed by the parent_hash, ordinal and hash. If we support multiple transactions in a block, we will implement new mechanisms(transaction pool) to guarantee their ordering and uniqueness.
