### ISSUE TITLE
RESTful APIs for blockchain and block access

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#731]
### Suggestion details

In order to facilitate integration with other apps, RESTFul APIs for accessing the blockchain and it's blocks need to be implemented. The following endpoints are strongly advised, but as is always the case, let the [bike shedding ](https://en.wikipedia.org/wiki/Law_of_triviality) commence.

It is advised that a hypermedia implementation be used (such as [JSONAPI](https://docs.rs/jsonapi/latest/jsonapi/) or [HAL JSON](https://www.innoq.com/en/articles/2020/12/rest-apis-with-hal/)) to help avoid said bike-shedding and bring industry benefits

### Transactions
`POST /transactions/ ` - This would return a `Location: /transactions/:id` and the transaction body payload which must also include the blockid. 
`OPTIONS /transaction/` - returns `204 OK` with `Allow: OPTIONS, GET, HEAD, POST`

`GET /transaction/:id` - returns the transaction
`OPTIONS /transaction/:id` - returns `204 OK` with `Allow: OPTIONS, GET, HEAD`
`HEAD /transaction/:id` - returns `200 OK` or `404 Not found`
`DELETE /transaction/:id` - **ERROR** `405 Method not allowed`
`PUT /transaction/:id` - **ERROR** `405 Method not allowed`
`PATCH /transaction/:id` - **ERROR** `405 Method not allowed`

### Blocks
`OPTIONS /blocks/` - returns `204 OK` with `Allow: OPTIONS, GET, HEAD`
`HEAD /blocks/` - returns `200 OK`
`POST /blocks` - **ERROR** `405 Method not allowed`  a block cannot be directly created
`PUT /blocks` - **ERROR** `405 Method not allowed`  a block cannot be directly created
`PATCH /blocks` - **ERROR** `405 Method not allowed`  blocks cannot be modified
`DELETE /blocks/` **ERROR** `405 Method not allowed`  blocks cannot be deleted

`OPTIONS /blocks/:id` - returns `204 OK` with `Allow: OPTIONS, GET, HEAD`
`HEAD /blocks/:id` - returns `200 OK` or `404 Not found`
`GET /blocks/:id` - returns a block by Id. Because transactions can be numerous they should be represented as hypermedia
`DELETE /blocks/:id` - **ERROR** `405 Method not allowed` a block cannot be deleted
`PUT /blocks/:id` - **ERROR** `405 Method not allowed` a block cannot be directly created
`PATCH /blocks/:id` - **ERROR** `405 Method not allowed` a block cannot be modified

`GET /blocks/:id/transactions/?submitter=` returns all transactions for a block as hypermedia links as there could be many. Usage of queryparams for filtering
`OPTIONS /blocks/:id/transactions` returns `204 OK` with `Allow: OPTIONS, GET, HEAD`
`HEAD /blocks/:id/transactions` returns `200 OK` or `404 Not found`
`GET /blocks/?submitter=` returns all blocks with a given submitter id, or if omitted, all blocks. Must be paginated. 

### Additional details

In order to strongly encourage direct people as to how blockchain works, even optional and unsupported verbs should be implemented (such as `OPTIONS` and `DELETE` on `/blocks/:id`)

**Comment by betarelease** [comment]
Currently the transparency log has all the block updates. So we can query the transparency log to get the relevant bits. Hence this ticket is now obsolete
