### ISSUE TITLE
Implement limited Key management

### ISSUE THREAD

**Issue by chb0github** [pyrsia/pyrsia#732]
### Suggestion details

In the blockchain world, everything is on the blockchain and information relevant to the proper functioning of the blockchain is also on the blockchain

In order to manage aspects of the the blockchain (such as the ability to add an authoritative key), a limited set of functionality around key management must be implemented.

### basic functionality
- [ ] Add Key (with authorities?)
- [ ] Revoke Key (implies revoking all authorities)
- [ ] Revoke Authority
- [ ] Enumerating a list of authorities
- [ ] get a view of the current set of authorities for a key
- [ ] perform a key search

### REST APIs
These really represent a search of the blockchain around a given key. However, we want to offer a fixed means of getting at this data without putting the burden of forcing the user to know the query to do it (which might also change). 

Typically, such things are represented in databases as a [view](https://en.wikipedia.org/wiki/View_(SQL)) and the best blend of rest with this paradigm looks as below.

- [ ] `/views/keys/:id/authorities` should all records be returned or a unioned view?
- [ ] `/views/keys/?query` search for keys, but based on what criteria
- [ ] `/views/keys/:id` -

**Comment by fishseabowl** [comment]
This issue has been replaced by issue #780 to follow architecture documentation updates.
