### ISSUE TITLE
Connection attempt to PeerId failed with WrongPeerId on two ubuntu focal nodes in VMWare

### ISSUE THREAD

**Issue by PouncePenguin** [pyrsia/pyrsia#736]
### Steps taken/Steps to reproduce

- I pulled a VM Ware image for Ubuntu Focal Fossa from osboxes.org. 
- I then copied that VM Ware image to a second one. 
- I installed dependencies and pyrsia following the steps here: https://pyrsia.io/docs/tutorials/demo/
- Each node will startup fine on their own without any errors. Upon modifying the pyrsia service with the --peer option and restarting the service, I see the following in the relevant syslog. 

**node 2:**
Connection attempt to PeerId("12D3KooWFSSFZgEgWoX8iLbbBrDgaSQeHMXvV812Ug4yo4GJe2s9") failed with WrongPeerId { obtained: PeerId("12D3KooWFSSFZgEgWoX8iLbbBrDgaSQeHMXvV812Ug4yo4GJe2s9"), endpoint: Dialer { address: "/ip4/192.168.171.137/tcp/44000", role_override: Dialer } }.

**node 1:** 
Incoming connection failed: WrongPeerId { obtained: PeerId("12D3KooWFSSFZgEgWoX8iLbbBrDgaSQeHMXvV812Ug4yo4GJe2s9"), endpoint: Listener { local_addr: "/ip4/192.168.171.137/tcp/44000", send_back_addr: "/ip4/192.168.171.138/tcp/38092" } }

_The configs are as follows:_
**node 1:**
pyrsia -c --show
host = 'localhost'
port = '7888'
disk_allocated = '5.84 GB'

ip addr show:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:2f:55:bc brd ff:ff:ff:ff:ff:ff
    altname enp2s1
    inet 192.168.171.137/24 brd 192.168.171.255 scope global dynamic noprefixroute ens33
       valid_lft 1217sec preferred_lft 1217sec
    inet6 fe80::3ff9:9c4b:ce0:7d7d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:4b:d9:05:84 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

pyrsia status:
Connected Peers Count:       0
Artifacts Count:             0 {}
Total Disk Space Allocated:  5.84 GB
Disk Space Used:             0.0002%

**node 2:**
pyrsia -c --show
host = 'localhost'
port = '7888'
disk_allocated = '5.84 GB'

ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:99:f7:60 brd ff:ff:ff:ff:ff:ff
    altname enp2s1
    inet 192.168.171.138/24 brd 192.168.171.255 scope global dynamic noprefixroute ens33
       valid_lft 1323sec preferred_lft 1323sec
    inet6 fe80::88eb:2acb:4330:ea45/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:f4:68:5a:9a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

Peer config in pyrsia service:
[Unit]
Description=Pyrsia Node

[Service]
WorkingDirectory=/usr/local/var
Environment="PYRSIA_ARTIFACT_PATH=/usr/local/var/pyrsia"
Environment="RUST_LOG=debug"
ExecStart=/usr/bin/pyrsia_node --host 0.0.0.0 -L /ip4/0.0.0.0/tcp/44000 --peer /ip4/192.168.171.137/tcp/44000

[Install]
WantedBy=multi-user.target

pyrsia status:
Connected Peers Count:       0
Artifacts Count:             0 {}
Total Disk Space Allocated:  5.84 GB
Disk Space Used:             0.0002%

### Expected Behavior

I was following along with Sudhindra's demo here: https://www.youtube.com/watch?v=28T_sQDYhXE&list=PL7T9WKeqA8taQtJJrc73UB_oYYb6uyhBS. I was expecting to see the nodes peer in the logs and when running pyrsia -s.

### Experienced Instance of the bug

Operating System:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

Pyrsia:
pyrsia_cli 0.1.1 (716ac70c74a0a375ae0ee04b3d2da8b349a82442)

**Comment by betarelease** [comment]
@PouncePenguin Thanks for the details. Also thanks for confirming the ubuntu version you are trying with(plus the platform)

Do you have the ability to try this on AWS/Google Cloud just to verify if it works there? I have tried it on Google cloud and I was able to make it work(one thing I do remember doing is to open up ports for the VMs so that communications from Peer nodes can happen - I am not sure how that is to be done on VMware, but please make sure the ports are opened and accessible)

@tiainen can you take a look when you are back online? See if there is a hint in the code about what this would happen.

**Comment by PouncePenguin** [comment]
@betarelease Yes, I can try it on AWS. It'll be a bit, but will try to do that tonight. The ports should be accessible as I can netcat from one node to the other on the relevant peering port, but I will run a network trace to see if that gives any additional info.

**Comment by betarelease** [comment]
yeah that would be super helpful. We do not have a VMware setup to try this out so we will need someone with access like you do to help us test.

**Comment by betarelease** [comment]
We do have a community meeting tomorrow at 10am PST. If you do have the time you can join there and show us with screenshare if you can and ask questions.

**Comment by PouncePenguin** [comment]
@betarelease I was able to get further on AWS for sure. I was able to configure node 2 with peering to node 1. Upon restarting the pyrsia service, I can see a successful connection in the logs. I can also run a pyrsia -s or a pyrsia -l and see that the nodes are connected to one another; however, after about 30 seconds, I see the following error on node 1:

May 27 02:05:45 ip-172-30-3-131 pyrsia_node[4551]:  DEBUG libp2p_swarm                                   > Connection closed with error KeepAliveTimeout: Connected { endpoint: Dialer { address: "/ip4/172.30.3.212/tcp/44000/p2p/12D3KooWNv2cAaUC4NmcApFkSieBt2F1XUjX7fKquKbL8yPRgv8G", role_override: Dialer }, peer_id: PeerId("12D3KooWNv2cAaUC4NmcApFkSieBt2F1XUjX7fKquKbL8yPRgv8G") }; Total (peer): 0.

and the following error on node 2:
May 27 02:05:45 ip-172-30-3-212 pyrsia_node[4422]:  DEBUG libp2p_swarm                                   > Connection closed with error KeepAliveTimeout: Connected { endpoint: Listener { local_addr: "/ip4/172.30.3.212/tcp/44000", send_back_addr: "/ip4/172.30.3.131/tcp/44794" }, peer_id: PeerId("12D3KooWLR5Jof4uiLeE7sCACZNmAQCAPXTf8tZCfEFLjpBjPCCA") }; Total (peer): 0.

However, when I run prysia -s and pyrsia -l on each node, I see the following:

node 1:
ubuntu@ip-172-30-3-131:~$ pyrsia -s
Connected Peers Count:       1
Artifacts Count:             0 {}
Total Disk Space Allocated:  5.84 GB
Disk Space Used:             0.0002%
ubuntu@ip-172-30-3-131:~$ pyrsia -l
Connected Peers:
["12D3KooWNv2cAaUC4NmcApFkSieBt2F1XUjX7fKquKbL8yPRgv8G"]

node 2:
ubuntu@ip-172-30-3-212:~$ pyrsia -s
Connected Peers Count:       1
Artifacts Count:             3 {"manifests": 1, "blobs": 2}
Total Disk Space Allocated:  5.84 GB
Disk Space Used:             0.0484%
ubuntu@ip-172-30-3-212:~$ pyrsia -l
Connected Peers:
["12D3KooWLR5Jof4uiLeE7sCACZNmAQCAPXTf8tZCfEFLjpBjPCCA"]

I pulled down the alpine docker image on node 1. I then pulled the image on node 2 and I can see in the logs that it was successfully added to the pyrsia registry.; however, the logs indicated that the image wasn't found in the registry on node 1 When I then remove the image and re-pull it on node 1, it downloads and seems to add it to the local registry, but doesn't seem to check the peer.

**Comment by PouncePenguin** [comment]
I was able to follow https://docs.rs/libp2p/0.44.0/libp2p/tutorials/ping/index.html and setup a peering network between the two vm images. The peering established correctly between them when using just the libp2p Rust library.

I tried removing the network adapters on each of the vm images to see if this would help.  There wasn't a change in behaviour.

**Comment by fishseabowl** [comment]
@PouncePenguin  Thanks for the details. This problem is because nodes A and B use the same key file. Could you delete the key file p2p_keypair.ser on both nodes and restart the service?

**Comment by PouncePenguin** [comment]
@fishseabowl Thank you very much. That has resolved the peering. I'm sorry that I didn't notice the key file before. I would have tried that. I'm getting a new issue now, but will do some debugging before asking for assistance. Should I log a PR to update documentation for the steps above?

**Comment by fishseabowl** [comment]
@PouncePenguin Sure. It would be greatly appreciated if you could open a PR to update the documentation. Thank you very much for taking the time to try Pyrsia.
