### ISSUE TITLE
repo settings: Enable "delete head branches" on PR merge?

### ISSUE THREAD

**Issue by adamdmharvey** [pyrsia/pyrsia#752]
### Suggestion details

Wonder it it might be a good idea to turn on "delete head branches" in the repo settings.

I noticed when my PRs are merged, my branches hang out there:

> <img width="996" alt="image" src="https://user-images.githubusercontent.com/33203301/171675157-f3dfc118-6418-4f8d-ae3f-c69b2a45db96.png">

With my projects, we frequently turn on "delete head branches" which really helps in terms of the collaborators within the project to reduce branch complexity, but frequently even with open source contributors, to just help reduce later technical debt on their stale branches.  It doesn't yet look like this repo is using any fancy branching strategies (dev, release, etc) but even if that's done later, if those get protected, delete head branches feature won't touch those so they can ensure those aren't affected (accidentally deleted with a PR merge for example).

Just a possible suggestion!

> <img width="569" alt="image" src="https://user-images.githubusercontent.com/33203301/171675609-52c7421d-e5a1-49a0-8fb1-ba21eb56e688.png">

### Additional details

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by prince-chrismc** [comment]
Hmm it was already on 🤔 

![image](https://user-images.githubusercontent.com/16867443/171676429-c8f08dab-6a71-46a5-bed3-0658e5798c74.png)

I think it might not work on forks, it seems to work on local branches https://github.com/pyrsia/pyrsia/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies
