### ISSUE TITLE
Follow-up on NAT PRs and define next steps

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#762]
PR #712 contains some work on NAT traversal that needs to be reviewed. On top of that, we need a good overview of what our NAT capabilities currently are, and what we are missing to do at least to most simple form of NAT traversal: using the central node as a relay.

**Comment by erwin1** [comment]
I had to revert https://github.com/pyrsia/pyrsia/pull/712 because it broke the demo scenario. (it needs an extra --mode param and I had a panic when I used --mode none)

It can be re-introduced once we have validated and fixed that and adapted the documentation if necessary

**Comment by betarelease** [comment]
Follow up of the work from #584

**Comment by betarelease** [comment]
Is this complete @efrisch ? do we have the followup tasks written down as issues?

**Comment by efrisch** [comment]
Yes. #943 and #944 --- I think we can close this
