### ISSUE TITLE
OS/X Tests failing in Rust Workflow

### ISSUE THREAD

**Issue by sbtaylor15** [pyrsia/pyrsia#775]
### Steps taken/Steps to reproduce

See https://github.com/pyrsia/pyrsia/runs/6834541160?check_suite_focus=true

```
test util::env_util::tests::test_value_empty ... ok
error: test failed, to rerun pass '-p pyrsia --lib'
test util::env_util::tests::test_value_present ... ok
test util::keypair_util::tests::load_existing_keypair_succeeds ... ok
test util::keypair_util::tests::load_existing_keypair_with_wrong_size_fails ... ok
test util::keypair_util::tests::load_non_existing_keypair_fails ... ok
test util::env_util::tests::test_value_present_trim ... ok
test util::keypair_util::tests::saved_keypair_can_be_loaded ... ok
test node_manager::handlers::tests::quality_metric_test ... ok
failures:
---- node_manager::handlers::tests::network_load_test stdout ----
thread 'node_manager::handlers::tests::network_load_test' panicked at 'assertion failed: qm2 > qm', src/node_manager/handlers.rs:423:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected Behavior

All tests should pass

### Experienced Instance of the bug

Rust Workflow fails on OS/X tests.

**Comment by fishseabowl** [comment]
@sbtaylor15 It is similar to #643. Unit tests fail randomly.

**Comment by betarelease** [comment]
Verify if these are still failing.

**Comment by betarelease** [comment]
@dasmanas can you verify if these are still failing, If not please add your report here and close this issue.

**Comment by betarelease** [comment]
Can you also check what is happening with #632 and if you are able to see those errors at all?

**Comment by fishseabowl** [comment]
Different test cases in latest commit fail (PR #939)
```
failures:

---- peer_metrics::metrics::tests::disk_load_test stdout ----
thread 'peer_metrics::metrics::tests::disk_load_test' panicked at 'assertion failed: qm2 > qm', src/peer_metrics/metrics.rs:196:9


failures:
    peer_metrics::metrics::tests::disk_load_test

test result: FAILED. 106 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.07s

error: test failed, to rerun pass '-p pyrsia --lib'
Error: Process completed with exit code 101.
```

**Comment by dasmanas** [comment]
Another instance of` peer_metrics::metrics::tests::disk_load_test` failing
https://github.com/pyrsia/pyrsia/runs/7869961085?check_suite_focus=true

**Comment by dasmanas** [comment]
Test case simulates network and disk load. It measures network and disk stress before and after the execution of load. It expects load measures after the stress will be always higher than the load measured before. It mightn't hold good always. It requires further discussion.

**Comment by betarelease** [comment]
I think @mseabornIBM can help with this test since it was done as part of peer-metrics

Also running these tests separately from the unit tests is an option.

**Comment by dasmanas** [comment]
It got fixed. This doesn't fail anymore.
