### ISSUE TITLE
New authorized nodes can be added to the Pyrsia network

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#780]
We need to start with the definition of an authorized node: an authorized node is a node for which a transaction exists in the transparency log with operator 'add_node' and for which no later transaction 'remove_node' exists.

So to bootstrap a Pyrsia network, we need a node that has 1 transaction including the 'add_node' referencing its own node id.

- As an authorized node admin I can add a candidate authorized node **[CLI]** **[TRANSPARENCY_LOG]** **[BLOCKCHAIN]**

    The authorized node marks the new node id as an authorized node 'candidate' and
    creates an `add_node` transaction request and waits for consensus.
    Consensus might not be reached yet, but the authorized node keeps the candidate
    so a future transaction request from another authorized node might reach consensus.

    A transaction payload might look like this:
    { 
        operation: 'add_node',
        pyrsia_id: '<node-id-of-the-authorized-node-candidate>',
        timestamp: 12345
    }

    Questions to answer:
    - how do we know the other authorized nodes (the blockchain component could look up all 'add_node' transactions, but it might be better to have the transparency_log component handle this)
    - how are transaction requests sent to other authorized nodes?
    - where to store the candidate node ids?

- When a Transaction request is received all authorized nodes participate in the consensus mechanism **[BLOCKCHAIN]**

  Other authorized nodes validate transactions based on the transaction's operation
  type. Examples of transaction operations:

    - `add_node`: to add a new authorized node. see 'add_node transaction requests are handled'
    - (for now, other operation types left out for clarity)

- add_node transaction requests are handled **[BLOCKCHAIN]**
  an `add_node` transaction requests follows this procedure:

  - was the node previously marked as an authorized node candidate?
  - if yes, the authorized node answers positively in the consensus algorithm

- When consensus is reached, the transaction is committed to the blockchain. **[BLOCKCHAIN]**
  As a result, all nodes must receive new transactions.

Test scenario:

1. Start a bootstrap node (node A) including an add_node transaction for its own id.
2. Start 3 other nodes (node B, C and D) and p2p connect them to node A
3. Using the CLI on node A, request the addition of node B, C and D as an authorized nodes
4. Node A identifies itself as the only authorized node and approves the transactions (TODO: not sure if this is possible), adds them to the blockchain and makes sure the blocks are distributed to the other nodes. All nodes are now authorized nodes.
5. Start another node E and request the addition of it as authorized node on Node A. The result should be no consensus but node A will have marked node E as a candidate.
6. Request the authorization of node E on node B. The result should again be no consensus but node B will have marked node E as a candidate.
7. Request the authorization of node E on node C. The result should again be consensus and node E will be authorized as well.

**Comment by fishseabowl** [comment]
Suppressed by [latest architecture documentation](https://github.com/pyrsia/pyrsia/blob/main/docs/developers/pyrsia-architecture-and-use-cases.md).
