### ISSUE TITLE
Reproducible builds prototype

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#794]
Explore and prototype building reproducible artifacts so we can:
* define the interface of the Build and verification service inside the Pyrsia node
* define the requirements for a real build pipeline

**Comment by tiainen** [comment]
Just for reference, this is the flow as it was implemented for the prototype:

1. `pyrsia_cli` requests a build from source: `pyrsia build maven --gav groupId:artifactId:version`
2. the request is handled by `pyrsia_node`'s http server
3. `pyrsia_node` delegates the request to `artifact_service.request_build()`
4. `artifact_service` emits a build event: `BuildEvent::Start`
5. `build_event_loop` handles the event and invokes `build_service.start_build()`
6. `build_service` asks `mapping_service` for a mapping info
7. `mapping_service` creates a mapping info based on the build request:
    1. docker build: a basic mapping info is created
    2. maven build: the mapping info is looked up in the git repository https://github.com/pyrsia/pyrsia-mappings
8. `build_service` makes an http request to the correct `build_pipeline`
9. `build_pipeline` receives the http request and creates a `BuildInfo` with a unique id and status `Running`
10. `build_pipeline` starts the build as a bash process in a separate thread and waits for the result
11. `build_pipeline` responds to the http request with the created `BuildInfo`
12. `build_service` receives the response and starts a new thread to check the build status
13. `build_service` asks the current status from `build_pipeline`
14. `build_service` checks `build_info.status`:
    1. `Running`: wait 5 seconds and execute step 13 again
    2. `Failed`: `build_service` emits a build event `BuildEvent::Failed`
    3. `Success`: go to step 15
15. `build_service` processes the successful build status which also comes with a list of built artifacts
16. `build_service` will for each artifact:
    1. generate its package specific artifact id (PSAID)
    2. download it from `build_pipeline`
    3. calculate its hash
17. `build_service` collects all this info in a `BuildResult` and emits the build event `BuildEvent::Succeeded`
18. `build_event_loop` handles the event and invokes `artifact_service.handle_build_result()`
19. `artifact_service` will for each artifact in the build result:
    1. invoke `transparency_log_service.add_artifact()` to create a transparency log for the artifact
    2. ~~wait for `transparency_log_service` to have the transparency log created and committed to the blockchain~~ (not yet implemented!)
    3. push it to the local artifact storage
    4. provide it on the p2p network
