### ISSUE TITLE
Implement inspect transparency log command

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#871]
Add a new CLI command named `inspect-log` taking the package specific id as a parameter.

This will query the transparency log database and output all found transparency logs (most recent first) in JSON format.

Use the same structure for the CLI commands as the build command. Example
```
pyrsia inspect-log maven --gav groupId:artifactId:version
```

Note: this could result in more than one 'add_artifact' transparency log, because one Maven artifact (identified by groupId:artifactId:version) will consist of multiple Pyrsia artifacts. (pom.xml, jar, ...)

UPDATE: since #869 we also have tranparency logs for docker images, so this should be supported by the CLI as well

**Comment by betarelease** [comment]
Is this similar to #688 ?
