### ISSUE TITLE
Store and fetch multiple documents

### ISSUE THREAD

**Issue by tiainen** [pyrsia/pyrsia#89]
At the moment, the implementation of the document store has the following limitations:

1. store the first index that is detected in a document
2. storing a document overwrites the previous index for identical index values
3. fetch a single document for a given index

The implementation should be updated to support the following cases:

1. store each index that is defined for a document store
2. store multiple documents that have an identical index value
3. return a list of matching documents

**Comment by mgrand** [comment]
@tiainen The behavior you describe is not what we want. An attempt to insert a record that would duplicate an index record needs to be rejected. I am currently in the process of documenting this in https://github.com/pyrsia/pyrsia/issues/126.

Consider this use case: we want to update the collection of versions in a packages. The outcome of doing that should be that there is one package record, but its `versions` field contains an additional version string.

Please close this and you can do #126 after #125.
