### ISSUE TITLE
Work with the libp2p rust team to figure out a solution for owning_ref vulnerability

### ISSUE THREAD

**Issue by betarelease** [pyrsia/pyrsia#921]

**Comment by AbhijithGanesh** [comment]
The issue can be attributed to [RUSTSEC-2022-0040](https://rustsec.org/advisories/RUSTSEC-2022-0040.html) where the package `Owning_Ref` uses unsound rust methods that can lead to memory corruption! The dependency which causes this is `LibP2P` which uses `Prometheus` related libraries which use `Owning_Ref` as a part of its dependencies

**Comment by AbhijithGanesh** [comment]
As per my understanding of the usage of [prometheus_client](https://docs.rs/prometheus-client/0.17.0/prometheus_client/) by LibP2P they use this crate through 14 files(I will attach those files as a thread here!) These files use functionalities which are being offered by various libraries, two of them which caught my attention were [the official Prometheus Crate](https://github.com/prometheus/client_rust) and the client offered by an organization called [Tikv](https://docs.rs/crate/prometheus/0.13.1) which have fixed the problems! we can send in a PR to the LibP2P team patching those changes

**Comment by AbhijithGanesh** [comment]
update: LibP2p does use the official crate! The official crate has unsafe issues with `Owning_Ref`

**Comment by AbhijithGanesh** [comment]
![image](https://user-images.githubusercontent.com/67182544/182778103-3bd91560-d4b8-4b12-abd9-50dda988c56e.png)

The prometheus_client for Rust uses `MutexGuard` and `Owning_Ref` was a crate that offered a solution back then!

**Comment by betarelease** [comment]
This is now fixed and resolved in https://github.com/libp2p/rust-libp2p/issues/2794. We will take this update by testing it ourselves and not through dependabot. Closing this issue and we will have a new issue created when we decide to upgrade to 0.47
