### ISSUE TITLE
User Documentation: Improve website's Good PR Page

### ISSUE THREAD

**Issue by badesiru** [pyrsia/pyrsia#929]
### Suggestion details

- In the document design section of the Good PR page the wording of this sentence should be changed “document design decision in the docs/ folder of write a blog for the website”. I didn’t understand what this sentence was supposed to mean
- Small typo “Keep the changes small, limit the scope of the PR to make it clear an concise” change it to “clear and concise”

**Comment by AbhijithGanesh** [comment]
@badesiru Welcome to Pyrsia! We are actively working on enhancing the documentation for the project! Would you like to send in a PR to fix this patch?
