### ISSUE TITLE
Create an initial implementation of the metadata manager

### ISSUE THREAD

**Issue by mgrand** [pyrsia/pyrsia#95]
This task is to:
* Create and organize for use as signed structs the structs and enums used to represent metadata for:
  * package types
  * namespaces
  * package
  * package version
  * artifact
  
* Design the initial metadata manager API to support
  * create namespace
  * get namespace
  * get namespaces by package type
  * create package
  * get package
  * update package 
  * get packages by namespace
  * update package
  * create package version

* Implement the API to call the document store or a mock of it.

**Comment by mgrand** [comment]
Created a draft pull request for the first bullet.

**Comment by prince-chrismc** [comment]
> Created a draft pull request for the first bullet.

Can you please link the related pull request(s)?

**Comment by betarelease** [comment]
Marking as outdated. And closing.
