### ISSUE TITLE
Add support for distributed transparency log

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#956]
Integrate blockchain, transparency log, build service and verification service to support distributed transparency log.

> Error retrieving artifact: ID commons-codec/commons-codec/1.15/commons-codec-1.15.pom for type Maven2 not found in transparency log

The distributed transparency log is not yet implemented and pending on the work that is done on the blockchain. @fishseabowl might give more insight on progress or link to the correct issue.

_Originally posted by @tiainen in https://github.com/pyrsia/pyrsia/issues/936#issuecomment-1208961833_

**Comment by fishseabowl** [comment]
Completed in version 0.2

**Comment by betarelease** [comment]
Can you add the PR number that has this implementation ? Or if multiple PRs can you add them here.

**Comment by tiainen** [comment]
Implemented with https://github.com/pyrsia/pyrsia/pull/1047 and https://github.com/pyrsia/pyrsia/pull/1132
