### ISSUE TITLE
Providing a file blocks the Pyrsia node

### ISSUE THREAD

**Issue by erwin1** [pyrsia/pyrsia#988]
Since we do AutoNat bootstrapping by default, a locally started pyrsia node is automatically connected to the 'Pyrsia network'. 

As a result, I've found that when connected to the central node(s), providing files (e.g. after a build from source) on the p2p network blocks the Pyrsia node from doing anything else.

Steps to reproduce:

- follow the instructions in one of the build from source tutorials (https://pyrsia.io/docs/tutorials/build_from_source_maven/)
- after the build succeeds and the files are provided on the network, try to run: `pyrsia -s` (or hit http://localhost:7888/status)
- The result is that this last command will hang, waiting for something happening inside Pyrsia.

Alternatively, this can be reproduced by simply starting a node:
```
RUST_LOG=debug DEV_MODE=on PYRSIA_ARTIFACT_PATH=/tmp/pyrsia cargo run --package pyrsia_node
```

and then run curl http://localhost:7888/peers

it then gets stuck in p2p_client.list_peers().await

**Comment by erwin1** [comment]
Keep also in mind that in milestone 0.2 we do not have to support a full featured behind-a-NAT pyrsia node. it would be enough to have a behind-a-NAT node, connect to one of the central nodes and be able to download from the Pyrsia network. It does not necessarily need to participate in the content distribution to other nodes itself.

**Comment by johanvos** [comment]
I can not reproduce the failure on Ubuntu 20.04 with rustc 1.62.0
I can reproduce the failure on Ubuntu 18.04 with rustc 1.63.0

**Comment by johanvos** [comment]
There is a `tokio::select` call in the eventloop which selects either a swarm event or a received command. The one that is not selected is dropped. I think it is better to process swarm events and received commands in 2 event loops.
