### ISSUE TITLE
No validation for 'pyrsia config --edit' values

### ISSUE THREAD

**Issue by karolh2000** [pyrsia/pyrsia#999]
### Steps taken/Steps to reproduce

It's possible to provide incorrect values for the pyrsia CLI config (host,  port, etc) as shown below:

```
user@macos  /tmp/pyrsia/target/release/pyrsia config --edit
Enter host: 
%*%*%*%*NONSENSE_AS_HOST@#$*@#$*@#$*
Enter port: 
flkasfkjlPORT_NUMBER2342342
Enter disk space to be allocated to pyrsia(Please enter with units ex: 10 GB): 
@#$@#$@#$
Node configuration Saved !!
user@macos /tmp/pyrsia/target/release/pyrsia config --show
host = '%*%*%*%*NONSENSE_AS_HOST@#$*@#$*@#$*'
port = 'flkasfkjlPORT_NUMBER2342342'
disk_allocated = '@#$@#$@#$'
```

The shown values should be rejected. Some sort of validation is needed when a user enters/updated the config.

### Expected Behavior

The validation rejects incorrect config values. 

### Experienced Instance of the bug

rustc 1.63.0 (4b91a6ea7 2022-08-08)
macos
2872c5cdbf679b64061946005712bba5002c9002

**Comment by dasmanas** [comment]
Valid domain value for Hostname, port & disk_allocated.
host = n.n.n.n | localhost | <what else>
port =  u16::MIN<=N<=u16::MAX
disk_allocated = [1 - 1024] GB

Is the above validation is good enough?
